### ISSUE TITLE
Grid cascade: left and max_cols not working together

### ISSUE THREAD

**Issue by blubberbo** [BTMorton/angular2-grid#107]
hi,

I have a grid with a max number of columns and I would like the items to fill the first row, then the second row and so on. I tried using 'cascade' : 'left' but the combination of that and 'max_cols' does not limit the number of columns. 

With just 'cascade' : 'left' it works or with just 'max_cols' : 2 it works, but not with both of them together

any thoughts?

**Comment by wuhkuh** [comment]
Are you getting an output from your browser? If so, please post it here.
I can't reproduce the problem myself. Could you post a plunker?

**Comment by wuhkuh** [comment]
I made a hotfix for the issue. It will be uploaded soon as a pull request.
