### ISSUE TITLE
Updating to rc4

### ISSUE THREAD

**Issue by kelvinlouis** [BTMorton/angular2-grid#110]
Hey guys,

Are there plans to update to rc4? Or has anybody experienced issues using it with rc4?

**Comment by kelvinlouis** [comment]
I have been using it now for a while and it seems to work perfectly fine. I haven't used all the features yet, but so far so good. Does anyone know of any issues?

**Comment by brechtbilliet** [comment]
Works fine on rc4 @kelvinlouis There are a few issues with resizing but that could be my fault ;)

**Comment by kelvinlouis** [comment]
Yeah, I haven't experienced anything major so far. Sometimes while resizing the row count just explodes. But I can live with that :)
