### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Abubarrett** [BTMorton/angular2-grid#114]
Hi guys, I've been trying to install your grid and the whole configuration works until I try to add the Directives to the component. On sublime It even finds the right files:

<img width="1592" alt="screen shot 2016-07-20 at 3 42 29 pm" src="https://cloud.githubusercontent.com/assets/16496489/17002429/da3256ee-4e90-11e6-83b0-97c2f0886d53.png">
<img width="1592" alt="screen shot 2016-07-20 at 3 42 22 pm" src="https://cloud.githubusercontent.com/assets/16496489/17002439/e5aced04-4e90-11e6-9385-781ee2d8a916.png">

I'm also attaching a screenshot of the config file, I'm using angular-cli.

<img width="1592" alt="screen shot 2016-07-20 at 3 42 33 pm" src="https://cloud.githubusercontent.com/assets/16496489/17002461/ff568e22-4e90-11e6-8bdb-668ac0bafa7d.png">

But when I add the directives to the @Component, the whole thing breaks haha *ONLY when i add the directives to the component, not before which would tell me the system config is fine?* , any ideas?
![screen shot 2016-07-20 at 3 46 57 pm](https://cloud.githubusercontent.com/assets/16496489/17002500/370ffa2e-4e91-11e6-97b6-f47b264b358d.png)

**Comment by wuhkuh** [comment]
Okay, this part is missing:

> To use with angular-cli, you will also need to add the following to the vendorNpmFiles array in angular-cli-build.js:
> 
> 'angular2-grid/dist/**/*.js'

**Comment by Abubarrett** [comment]
I also did that and it does add the folder 'angular2-grid' to dist/vendor (forgot to mention that part before) but the error is still there. I figured since it copies the files to dist/vendor/angular2-grid, i would maybe change the system-config link to `map: {
    'angular2-grid': 'vendor/angular2-grid/dist/'
  },`, but still doesn't work.

**Comment by wuhkuh** [comment]
Could you change the system config to what you just posted and post the output you're receiving in your browser? Please rebuild the application after a change and restart the server - then hit F5 on your browser. Sorry if you're already doing that, I want to make sure everything is working properly.

**Comment by Abubarrett** [comment]
It's ok haha thanks for helping. I actually fixed it by leaving the map to `'angular2-grid': 'vendor/angular2-grid/dist/'` and adding the line `cliSystemConfigPackages['angular2-grid'] = { main: 'main.js',  defaultExtension: 'js' };`  instead of adding the package to system.config. Screnshot if any one ever finds the same issue haha.
<img width="1592" alt="screen shot 2016-07-20 at 5 15 48 pm" src="https://cloud.githubusercontent.com/assets/16496489/17005098/fba057c4-4e9d-11e6-84c2-d7ba15523bb7.png">

**Comment by BTMorton** [comment]
Thanks for that @Abubarrett, @wuhkuh. I'll update the readme with those extra changes
