### ISSUE TITLE
npm install error: reflect-metadata version

### ISSUE THREAD

**Issue by dmitrynovik** [BTMorton/angular2-grid#118]
$ npm install angular2 systemjs
npm WARN peerDependencies The peer dependency reflect-metadata@0.1.2 included from angular2 will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "angular2" "systemjs"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package reflect-metadata@0.1.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.17 wants reflect-metadata@0.1.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\code\angular2-grid\npm-debug.log

**Comment by BTMorton** [comment]
What is it that you're trying to do here? Are you trying to set up a dev build? It currently uses the `@angular` packages now that Angular 2 is in release candidate. It should all have been included with a regular npm install.
