### ISSUE TITLE
NgGridItem with button not handling clicks

### ISSUE THREAD

**Issue by critchie** [BTMorton/angular2-grid#121]
I'm trying to build a tile for a dashboard and want to include a close button at the top.  Placing the close button in a header at the top of the tile is easy enough but the click event is captured by the grid and never received by the button.  Because of this, the method in the component class is never executed.

Here is an example of a button in the grid item:

```
<div class="grid"
     [ngGrid]="{'max_cols': 6, 'max_rows': 6, 'auto_resize': false}">
  <div class="grid-item" [ngGridItem]>
    <button (click)="onRemoveClick()">
      Test
    </button>
  </div>
</div>
```

onRemoveClick() is never called.

Note: I am using the fixed_items branch as I needed the functionality in this code base.

**Comment by wuhkuh** [comment]
What version are you using? I have fixed this problem in a recent pull request - #113

**Comment by critchie** [comment]
OK... disregard.  I needed the fixed functionality out of the fixed_items branch so I was using it.  I didn't realize all of that had been worked into the main branch under the "fixed" property og NgGridItemConfig.

However...

I can still drag from my button.  That is, if I click and hold on my button I can drag the grid item.  And the click event still fires the onRemoveClick().  I tried to stop the click event in my code using stopPropagation but that didn't work.

Also... 
In the current code base - Line 1182 of NgGrid.ts:
this._renderer.setElementStyle(this._ngEl.nativeElement, 'width', '100%');//(maxCol * (this.colWidth + this.marginLeft + this.marginRight))+'px');

This is causing the grid items to "overflow" the grid.  You can see this if you give the grid a background color.  I have auto_resize set to false because I don't want the responsiveness auto_resize=false gives.

Removing the 100% and adding back the commented code seems to fix the overflow issue.

**Comment by critchie** [comment]
This has become a bit tricky actually.  I'm trying to build a tile that can be closed like a typical dashboard:

![image](https://cloud.githubusercontent.com/assets/340046/17295437/217c6264-57ca-11e6-9ad9-db7c195e6af9.png)

Clicking the close button in the upper-right seems to work fine with Chrome.  I can click anywhere on it and the tile closes.  But with Edge and Firefox clicking in the area of the red box causes a resize event to be fired and the click on the button doesn't get through.

Clicking on the button next to the "Data goes here" works fine all the time in all browsers.

I believe because the click is within the threshold of the resize area, a resize event is capturing the click and doing its thing and the button never gets the click.

**Comment by wuhkuh** [comment]
The first thing that comes to my mind is that we should move the resize function to the onMouseMove function as well - not just the drag function. @BTMorton

**Comment by wuhkuh** [comment]
After some more thinking I realized that the best solution would be to stop event propagation. The solution I mentioned above would be like getting a howitzer to a pistol fight.

Try something like

`<div class="gridbutton" (click)="stopProp($event)" (mousemove)="stopProp($event)"></div>`

`    
stopProp($event) {
        $event.stopPropagation();
    }
`

**Comment by OnlyAGhost** [comment]
This is super old and probably not relevant any more, but just in case...

I think that the ngGridItem supports a config setting to set the resize selector. If you did that would it prevent the resize from getting called in that area?

**Comment by BTMorton** [comment]
I've updated the resize/drag start handlers so it registers on mouse down but doesn't actually start the drag/resize process until mouse move. Should fix this issue :)
