### ISSUE TITLE
Send notification when cascading is done

### ISSUE THREAD

**Issue by dalibor-frivaldsky** [BTMorton/angular2-grid#134]
In my current scenario, I'm resetting the height of the `ngGrid` div when items are moved around/resized by reacting to the `onItemChange` event of the `ngGrid` component. The height is calculated as max of `item.top + item.height`. This works nicely.

The problem comes when I remove an item from the grid. The cascading logic properly rearranges the items, but does not emit any event for me to react to and recalculate the grid height. Performing the recalculation at the time of the item removal is too soon, because it triggers before the cascading logic kicks in.

**Comment by BTMorton** [comment]
The items actually publish an event any time they change. Have you tried binding to the `onItemChange` or `onChangeStop` events on the `ngGridItem`s themselves?

**Comment by kelvinlouis** [comment]
I noticed that the grid doesn't update its height anymore since 0.9.0. Whenever an item was removed, the entire grid recalculated its height. This used to work in 0.8.3. Has anyone else noticed this?

**Comment by BTMorton** [comment]
@kelvinlouis yeah, that's been referenced in #127

**Comment by dalibor-frivaldsky** [comment]
Sorry for taking so long to reply. As per your suggestion, I've tried to react to the `onItemChange` and `onChangeStop` event of the `ngGridItem`. The way it behaves is:
`onChangeStop` - is never fired when the items are being repositioned during cascading
`onItemChange` - does fire during cascading, but `row`/`col` properties of the items are reported as of the state before cascading. The height is thus recalculated from incorrect values.
