### ISSUE TITLE
Updated support for rc.6 added in new fork

### ISSUE THREAD

**Issue by OnlyAGhost** [BTMorton/angular2-grid#135]
Sorry, I have not done a lot of commits on GitHub so I know that I'm going about this the wrong way. In my fork I have the code updated to support rc.6 (added modules, replaced DynamicComponentLoader with componentFactoryResolver). I tested it in my application and it appears to be working properly, emitting, etc but I cannot figure out the automated testing process before submitting it to be pulled into master. If you let me know what I need to do there to make sure it's all working correctly I would be happy to!

**Comment by BTMorton** [comment]
Yeah, there's currently no automated testing for this repo (I know, I know, that's awful...). Just go ahead and open a PR, I'll check it out :)

**Comment by OnlyAGhost** [comment]
Ha! We keep telling ourselves we're going to add automated testing after this next feature enhancement...

Anyway I will submit the pull request. The demo will need to be updated for the new method, if anything looks amiss let me know and I'll update it and get it submitted!

**Comment by OnlyAGhost** [comment]
FYI, I updated my fork with some new code. Fixed the calls to index.html, had to fix some things in the module (needed to include FormsModule), just generally made it more in-line with the recent Angular changes. I also added lite-server, so in npm you can do npm run lite and it'll automatically start a webserver for the project. I tested running http://localhost:3000/src/index.html and it correctly shows the grid, allows you to add/remove/drag, etc.

**Comment by Luchillo** [comment]
@OnlyAGhost Dude here's your pull request url, i'm linking it so other people don't have to go looking in the pull request tab: https://github.com/BTMorton/angular2-grid/pull/136

Btw how's your fork doing? do you think is ready for an update?

I'm waiting for this in order to update my project to RC.6, i've tried installing directly from @OnlyAGhost git fork repo through npm, however it seems to alwasy download only the Readme and 2 other files, but source or dist code doesn't get downloaded.

**Comment by OnlyAGhost** [comment]
Yeah, I think other than the demo site needs updated it should be good to go.

What I did in my project temporarily was downloading the git repository and creating a folder in my code structure for angular2-grid and putting the dist folder in there and updating systemjs.config.js to point to my local copy instead of node_modules. That will let you test this code out while waiting for the pull request into the main tree.

**Comment by OnlyAGhost** [comment]
If anyone is trying what i suggested:

Clone the repository locally. Open that folder in command line and type the following and let each finish before running the next (obviously, but just in case):

npm install
typings install
gulp ts

The gulp process will build out the dist directory. If you wanted to test to make sure everything is good run:

npm run lite

Which will fire up the lite-server with browser sync. A browser will launch and it'll complain that it cannot reach /  (it doesnt have a config) so instead browse to /src/index.html and you should see a screen where you can add in grid items, resize, drag them, etc. If that's good, you can use that dist folder temporarily as once the PR is all cleaned up and ready to go that will be what is distributed via npm.

**Comment by Luchillo** [comment]
I see it is merged, i guess i'll try the original repo, @BTMorton  any ETA on this release?

**Comment by BTMorton** [comment]
It'll be out this evening. I'm just seeing if I can resolve any other issues this evening before I publish

**Comment by Luchillo** [comment]
Well i just cloned and for some reason the lite server is asking for the `node_modules` as if they were inside the `src` folder, with the steps declared by @OnlyAGhost in https://github.com/BTMorton/angular2-grid/issues/135#issuecomment-246807445.
![image](https://cloud.githubusercontent.com/assets/9698639/18493492/77640410-79d6-11e6-96f4-176d229d5e4f.png)

**Comment by OnlyAGhost** [comment]
Is there a / in front of the node_modules scripts in index.html? There needs to be otherwise it'll try and hit it relative to the path of the index html.

Those are the hard defined requirements and not the modules loaded in systemjs so it should be in the html.

Sent from my iPhone

On Sep 13, 2016, at 6:35 PM, Carlos Esteban Lopez Jaramillo <notifications@github.com<mailto:notifications@github.com>> wrote:


Well i just cloned and for some reason the lite server is asking for the node_modules as if they were inside the src folder, with the steps declared by @OnlyAGhost<https://github.com/OnlyAGhost> in #135 (comment)<https://github.com/BTMorton/angular2-grid/issues/135#issuecomment-246807445>.
[image]<https://cloud.githubusercontent.com/assets/9698639/18493492/77640410-79d6-11e6-96f4-176d229d5e4f.png>

-

**Comment by BTMorton** [comment]
try running lite-server in the `dist` folder. That should (hopefully) solve the problem. I'm going to add a lite-server config file for that very purpose. The reason I removed the `/`s was because I'm running it in on my sub-domain (which links directly to the `dist/` folder)

**Comment by BTMorton** [comment]
OK, I've just pushed those changes. Pull and restart. Should work fine :)

**Comment by Luchillo** [comment]
Not in office, testing thursday, thanks.

**Comment by Luchillo** [comment]
I've pull the latest changes, did go to the dist folder but since there's no html there after compilation it shows 404.

Maybe the one i should be searching is the `index.html` in the `demo` folder?
