### ISSUE TITLE
Drag not working with Safari

### ISSUE THREAD

**Issue by cyberbobjr** [BTMorton/angular2-grid#137]
Hi,
i've try with a personal test and  https://bmorton.co.uk/angular/ , dragging the ngGridItem not working with Safari v9.1.3

Many thanks for your good job,
best regards
cyb

**Comment by BTMorton** [comment]
Hi @cyberbobjr,

Unfortunately, I don't have access to a Mac at all to test this. I'll see if I can find someone to help resolve this, otherwise it's going to be on the community for contributions. Sorry about that.

Have you got any output from the console that might be of any use at all?

**Comment by ShipraGrover** [comment]
+1 doesn't work on safari

**Comment by cyberbobjr** [comment]
Hi @BTMorton , sorry nothing in the console. :(
