### ISSUE TITLE
Angular2 RC.7 runtime error

### ISSUE THREAD

**Issue by PivotalAnimal** [BTMorton/angular2-grid#138]
localhost/:33 Error: Error: Can't resolve all parameters for NgGrid: (KeyValueDiffers, ElementRef, Renderer, ?, ViewContainerRef).(…)

Hi, I can't figure out why I am getting this runtime error. My app.module looks something like this:

'import xyz
`import { NgGrid, NgGridItem } from 'angular2-grid';

@NgModule({
  imports: [ BrowserModule, HttpModule, routing, FormsModule ],
  declarations: [ StartComponent,  NgGrid, NgGridItem
   ],
   providers:    [ MyService ],
   bootstrap: [ StartComponent],
})
export class AppModule { }`

It happens during bootstrap: `System.import('app').catch(function(err){ console.error(err); });`

**Comment by BTMorton** [comment]
What version are you using? v0.10.0 was released last night which fixes the issues with RC5+ and this issue

**Comment by OnlyAGhost** [comment]
Try importing NgGridModule and see if that fixes that up.

**Comment by Luchillo** [comment]
I'm running 2.0.0 with this repo at 0.10.0 and it works like a charm.

**Comment by frederikschubert** [comment]
I think this issue can be closed.

**Comment by Luchillo** [comment]
I think so too, since has been 20 days since issue owner made anything, no comments, no responses, just close and if he still have the issue, he needs to comment to get it open again.

**Comment by PivotalAnimal** [comment]
Solved. Thanks!

**Comment by weishenghuang** [comment]
@PivotalAnimal 
I have the similar issue with you, could you share how did you solve this issue please??
