### ISSUE TITLE
No component factory found for NgGridPlaceholder

### ISSUE THREAD

**Issue by SundayLab** [BTMorton/angular2-grid#139]
Running the demo with Angular 2.0 final throws the following error.
The error is thrown when you start dragging the item.

**Comment by OnlyAGhost** [comment]
Would you be willing to test out if running the test via the lite server in npm and see if that is giving the same error? That would narrow down if the problem is in demo or something more upstream than that. I hadn't updated or tested demo so I could see something being there.

**Comment by cyberbobjr** [comment]
Same error here with Angular2 2.0
