### ISSUE TITLE
Online runkit demo is broken

### ISSUE THREAD

**Issue by willsheppard** [BTMorton/angular2-grid#143]
Starting here: https://www.npmjs.com/package/angular2-grid

Click the link marked **"Test angular2-grid in your browser."**

it loads page: https://runkit.com/npm/angular2-grid

That page displays an error:

```
Error: Cannot find module 'rxjs/Subject' 
```

**Comment by BTMorton** [comment]
Hey, I don't actually know how to change anything for the runkit page. It's nothing to do with me and is just an autogenerated npm thing, as far as I know. To see it running you can go to bmorton.co.uk/angular, or if you know how to fix the runkit stuff, let me know!
