### ISSUE TITLE
Cannot use with Angular AOT Compiler

### ISSUE THREAD

**Issue by frederikschubert** [BTMorton/angular2-grid#147]
To successfully compile an application that uses NgGridModule the `metadata.json` files produced by the ngc tool are needed in the npm distribution.
See [here](https://github.com/valor-software/ng2-bootstrap/commit/be1f851b1199cd89dbf31116167ebfb21225bae7) for an example of how this could work.

The error message when trying to run ngc is:

```
Unexpected value 'NgGridModule' imported by the module 'SomeApplicationModule'
```

**Comment by frederikschubert** [comment]
I got it working locally and would be happy to contribute the needed changes to the build system, if  you are not already working on this.

**Comment by lzoubek** [comment]
@frederikschubert can you share your local code (I haven't found it in your fork), I'd love to use this component with AOT.

Thank you

**Comment by jskrzypek** [comment]
I made [a PR](#168).

Until it's merged & released you can also pull in my fork, where I just exposed the `./dist` folder: https://github.com/jskrzypek/angular2-grid
