### ISSUE TITLE
Drag and drop between multiple container elements

### ISSUE THREAD

**Issue by paradite** [BTMorton/angular2-grid#150]
I don't see any existing documentation or issues touching on this so I just want to know if this is supported by the library? 

Basically I want to have elements (boxes) that can be moved between different container elements(with some event handlers). It would be similar to https://github.com/valor-software/ng2-dragula, but that library lacks the grid layout system.

If it is not supported by default, would it be easy to extend this library and implement it on my own? I can do it as a PR after implementing it.

Thanks.

**Comment by valdestrijus** [comment]
It is not supported. But if you want drag and drop some object from the objects pool or lets say you want to drag and drop components onto your grid which will have angular2-grid inside, you can do the following approach:
Tools:
ng2-dnd, angular2-grid

grid.component.html
```
<div class="droppable-container" 
	dnd-droppable 
	(onDropSuccess)="addWidget($event)" 
	[dropZones]="['widget-dropZone']">
	<div [ngGrid]="gridConfig" (onItemChange)="itemsChange($event)">
		<div class="widget-container grid-item" *ngFor="let widget of widgets; let i = index" [ngGridItem]="{
			sizex: widget.sizex,
			sizey: widget.sizey,
			row: widget.row,
			col: widget.col,
			maxRows: 6,
			payload: widget}" (onResize)="onResize($event)">
				<section>{{ myWidgetHere }}</section>
		</div>
	</div>
</div>
```

grid.component.ts
```
import { Component, Input } from '@angular/core';
import { Widget, WIDGETS } from '../../widgets';

@Component...
export class GridComponent {
         ...
	addWidget(event): void {
		let widget = _.cloneDeep(event.dragData);
		this.widgets.push(new Widget(widget));
	}

	itemsChange(items): void {
		.// do something with the model in this even handler
	}
}
```

widgets-pool.component.html
```
	<div class="custom-md-list-item" *ngFor="let widget of widgetPool" dnd-draggable [dragEnabled]="true" [dragData]="widget"
		[dropZones]="['widget-dropZone']">
		<button md-raised-button class="drag-and-drop-item">
			<md-icon md-list-icon
				fonticon="icon-drag-vertical"
				fontset="some-icon"
				role="img"
				class="md2 md-icon icon-drag-vertical"
				aria-label="fa-birthday-cake"
				ng-reflect-font-set="ahl-icon"
				ng-reflect-font-icon="icon-drag-vertical"></md-icon>
			<span md-line>{{ widget.name }}</span>
    	</button>
	</div>
```

widgets-pool.component.ts
```
import { Component, Input } from '@angular/core';
import { Widget, WIDGETS } from '../../widgets';

@Component...
export class WidgetPoolComponent {
        ...
	public widgetsMenu: Widget[] = WIDGETS;
}
```

**Comment by paradite** [comment]
@valdestrijus thanks for the suggestion. I have already developed an alternative solution to the problem. The source code is a bit complicated but I've written a blog post outlining the general approach if anyone is interested:

https://paradite.com/2016/10/17/building-angular-2-drag-and-drop-grid-system/
