### ISSUE TITLE
Drag not working in Safari on iPad

### ISSUE THREAD

**Issue by apadapin** [BTMorton/angular2-grid#154]
Hi,

I just tested the changes from pull request #148 in Safari on both Mac and iPad. On the Mac the fix works great, thanks. However, in Safari on the iPad (iOS 9.3.1) dragging is still not working.

**Comment by BTMorton** [comment]
Sorry about that! Was an issue with the changes to how drag/resize is started. Should be working in next release :)

**Comment by apadapin** [comment]
Thanks! Any idea when the next version will be released?
