### ISSUE TITLE
lifecycle event when done rendering grid

### ISSUE THREAD

**Issue by SundayLab** [BTMorton/angular2-grid#156]
Hi,

would by nice to have an event thats triggered when the grid is done with rendering. Really useful when you are adding boxes in a dynamic way.

**Comment by Strike117** [comment]
+1

**Comment by BTMorton** [comment]
What do you mean by rendering? When the grid has loaded the current items or when the cascading has finished?

**Comment by SundayLab** [comment]
well i think when cascading has finished i just need to know when the dom is complete

**Comment by SundayLab** [comment]
ok an angular lifecycle event does the job just did my stuff in `ngAfterViewInit()` works like a charme
