### ISSUE TITLE
Unable to drag/drop/resize in touch screens

### ISSUE THREAD

**Issue by theunreal** [BTMorton/angular2-grid#159]
I just noticed it's impossible to drag objects, drop, or resize them in touch screens.

Anyone has solution for it?

Tried to drag in my phone Chromw browser

**Comment by iinnaann** [comment]
I have also the same problem. It would be very nice, if we can drag and drop the objects

**Comment by BTMorton** [comment]
Sorry about that! Was an issue with the changes to how drag/resize is started. Should be working in next release :)
