### ISSUE TITLE
Cannot read property 'startMoving' of null

### ISSUE THREAD

**Issue by MartinJLee** [BTMorton/angular2-grid#165]
core.umd.js:2843 TypeError: Cannot read property 'startMoving' of null
    at NgGrid._resizeStart (NgGrid.ts:484)
    at NgGrid._onMouseMove (NgGrid.ts:531)
    at Wrapper_NgGrid.handleEvent (wrapper.ngfactory.js:80)

_getItemFromPosition could return null.
I guess we could simply return when it gets to null

**Comment by ankitw77** [comment]
When this error starts, then changes in the model doesn't get reflected in grid item.
Adding an undefined check seems to solve the issue.

Current :
---------
 NgGrid.prototype._resizeStart = function(e) {
     if (this.resizeEnable) {
         var mousePos = this._getMousePosition(e);
         var item = this._getItemFromPosition(mousePos);
         
         item.startMoving();
         this._resizingItem = item;
         this._resizeDirection = item.canResize(e);
         this._removeFromGrid(item);
         this._createPlaceholder(item);
         this.isResizing = true;
         this._resizeReady = false;
         this.onResizeStart.emit(item);
         item.onResizeStartEvent();
     }
 };

Fix :
----
 NgGrid.prototype._resizeStart = function(e) {
     if (this.resizeEnable) {
         var mousePos = this._getMousePosition(e);
         var item = this._getItemFromPosition(mousePos);

         if (item) {
             item.startMoving();
             this._resizingItem = item;
             this._resizeDirection = item.canResize(e);
             this._removeFromGrid(item);
             this._createPlaceholder(item);
             this.isResizing = true;
             this._resizeReady = false;
             this.onResizeStart.emit(item);
             item.onResizeStartEvent();
         }
     }
 };

**Comment by dunice-potapov** [comment]
Hello Ben @BTMorton ,

Can you please take a look on it and merge if all things are good?

Thanks,
Alexander
