### ISSUE TITLE
Cannot Install with Angular 2.2.x

### ISSUE THREAD

**Issue by jd-nfreitas** [BTMorton/angular2-grid#173]
Angular2-grid has a peer dependency on @angular/core: 2.1.1, preventing it from being installed with newer versions of angular. Please relax the peer dependency to allow installation with newer versions of angular. Are there any reasons for the 2.1.1 strict dependency?

**Comment by jd-nfreitas** [comment]
The peer dependency messages are warnings and do not prevent angular2-grid from installing. I'm closing this ticket.

**Comment by BTMorton** [comment]
Re-opening this ticket as it probably should be `"@angular/core": "2"` or similar so we don't get warnings :P

**Comment by remohy1** [comment]
It does not install with 2.1.1. Error angular2-grid@0.11.2 wants @angular/core@2.0.0. Demo is still using rc6. Can we use 2.1.1?

**Comment by BTMorton** [comment]
The peer dependency is now set to "^2.4.4" so should work with all the new angular releases. It's also a peer dependency, so it shouldn't block installation with npm 3+
