### ISSUE TITLE
Error: NgGridModule is not an NgModule with angular-cli

### ISSUE THREAD

**Issue by jinaraj** [BTMorton/angular2-grid#179]
Installed  angular2-grid and imported NgGridModule in my app module file. When I do ng build, I get the following error Error: NgGridModule is not an NgModule. Tried specifying the path in angular-cli.json ("scripts": ["node_modules/angular2-grid/dist/main.js", "node_modules/angular2-grid/dist/**/*.js"]). But I got the same error. My angular-cli version is 1.0.0-beta.22-1. Please help.

**Comment by valdestrijus** [comment]
You should clone this repo, manually build the project copy dist/aot folder to your angular-cli project somewhere in vendors catalog. Then in your app.module.ts or anywhere else where you are importing NgGridModule, use it like this: ```import { NgGridModule } from '../vendors/angular2-grid';```. To my knowledge aot-ready build is not released yet.

**Comment by kladier** [comment]
Hi @valdestrijus ,

We have exactly the same problem as jinaraj.
We did exactly what you said but it still doesnt work... 
Now we have this error "multi main" : 

> 
> ERROR in Error encountered resolving symbol values statically. Could not resolve ../vendors/angular2-grid relative to /home/what/svg-animator/src/app/app.module.ts., resolving symbol AppModule in /home/what/svg-animator/src/app/app.module.ts, resolving symbol AppModule in /home/what/svg-animator/src/app/app.module.ts
> 
> ERROR in ./src/app/app.module.ts
> Module build failed: Error: /home/what/svg-animator/src/app/app.module.ts (5,30): Cannot find module '../vendors/angular2-grid'.)
>     at _checkDiagnostics (/home/what/svg-animator/node_modules/@ngtools/webpack/src/loader.js:145:15)
>     at /home/what/svg-animator/node_modules/@ngtools/webpack/src/loader.js:172:17
>     at tryCatch (/home/what/svg-animator/node_modules/es6-promise/dist/es6-promise.js:410:12)
>     at invokeCallback (/home/what/svg-animator/node_modules/es6-promise/dist/es6-promise.js:425:13)
>     at publish (/home/what/svg-animator/node_modules/es6-promise/dist/es6-promise.js:393:7)
>     at flush (/home/what/svg-animator/node_modules/es6-promise/dist/es6-promise.js:121:5)
>     at nextTickCallbackWith0Args (node.js:419:9)
>     at process._tickCallback (node.js:348:13)
>  @ ./src/main.ts 5:0-45
 > @ multi main


"@angular/core": "^2.3.1"
"angular-cli": "1.0.0-beta.25.5"

**Comment by fonzy2013** [comment]
Great to see that more people than I have this issue. 
Do you know if the angular2-grid project is notified about this and if someone is working on it?

**Comment by NotBad4U** [comment]
The issue doesn't yet seem to have treated by @BTMorton  and nobody respond on stackoverflow [Angular2 Grid error](http://stackoverflow.com/questions/41684166/angular2-grid-error/41687852#41687852) but with @kladier we found a work around for our project (inject the component in your project like it is your, look like vendoring).

**Comment by BTMorton** [comment]
From looking at this issue report it seems to be potentially a version incompatibility with either angular-cli or typescript https://github.com/angular/angular-cli/issues/3426 There doesn't seem to be any actual solutions in there which is extremely unhelpful...

**Comment by NotBad4U** [comment]
Yeah seem to be a problem with `@angular/compiler-cli` and their version of typescript.

**Comment by BTMorton** [comment]
OK, so I've completely re-done my build steps following https://medium.com/@cyrilletuzi/how-to-build-and-publish-an-angular-module-7ad19c0b4464 and tried it with a symlink to your svg-animator project and it works. So now I need to backtrack the changes and figure out how to make it all work nicely... I'll get right on that...

**Comment by NotBad4U** [comment]
Thanks for the time spend @BTMorton

**Comment by BTMorton** [comment]
The latest release solves this issue. I have tested with https://github.com/BTMorton/angular2-grid-demo which is a new angular-cli project.

**Comment by fonzy2013** [comment]
great!!! thanks a million for the quick effort!

**Comment by jinaraj** [comment]
Thanks a lot!

**Comment by NotBad4U** [comment]
Thanks man !!
