### ISSUE TITLE
Maximum Grid Size

### ISSUE THREAD

**Issue by Nevergonnachange** [BTMorton/angular2-grid#187]
Hello,

It it possible to set a certain grid width and height so that the grid does not grow past these limits?

Pretty much like a dashboard that has only the screens size with no scrolling.

I have played around quite a bit with the grid settings but cannot get it to work as I'd like.

Thanks very much in advance.
NeverGonnaChange

**Comment by ajinkyau** [comment]
To set a certain grid size, I think "max_cols" / "max_rows" property under grid config would do the trick.

**Comment by FabienMercierSAH** [comment]
Hi,
We are trying ti use this one but even read the doc and questions/answers, we are unable to lock the main container size.
Can you explain us how to work with it ?
max_cols/max_rows seems to doesn't work and you are able to set only one of them.

We need to set the main container, for exemple to 200px height and width and lock the resize state even when you put an item outside of it. The outside item will automaticly set into the container or remove.

thanks a lots for your support.
FM
