### ISSUE TITLE
left/top resizing

### ISSUE THREAD

**Issue by truffle123** [BTMorton/angular2-grid#191]
Is it possible to resize gridItem from the left border for horizontal and from the top for vertical resize?
In this case it will resize item and change position.

**Comment by BTMorton** [comment]
Not currently, no. What were you thinking for?

**Comment by ThomasSchellenbergNextCentury** [comment]
Can't you just add statements to `canResize` and `onMouseMove`, like the following?
```
} else if (mousePos.right > 0 && mousePos.right < this._borderSize && mousePos.bottom > 0 && mousePos.bottom < this._borderSize) {
	this._renderer.setElementStyle(this._ngEl.nativeElement, 'cursor', 'nwse-resize');
} else if (mousePos.right > 0 && mousePos.right < this._borderSize) {
	this._renderer.setElementStyle(this._ngEl.nativeElement, 'cursor', 'ew-resize');
} else if (mousePos.bottom > 0 && mousePos.bottom < this._borderSize) {
	this._renderer.setElementStyle(this._ngEl.nativeElement, 'cursor', 'ns-resize');
}
```
Or are there other possible side effects?

**Comment by ThomasSchellenbergNextCentury** [comment]
I started to work on this issue in my fork here:
https://github.com/NextCenturyCorporation/angular2-grid/commit/4f9418cbd6348721d7963cd21b9023565d041378

However, NgGrid._resize needs to be updated as well to accommodate left and top resizing.
