### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by readme42** [BTMorton/angular2-grid#195]
It would be great if you could provide a changelog which lists especially all breaking changes.

Its not so easy to find out what happened from 0.11.2 to 1.x or from 1.x to the current [2.0.1 npm release](https://www.npmjs.com/package/angular2-grid).

And, by the way, bower and npm versions mismatch. Bower is 1.1.0, npm is 2.0.1.

**Comment by BTMorton** [comment]
Yeah, that was mostly my fuck up. The breaking change was how the distributed files are generated and published for angular-cli support. It should actually currently be 0.13.1 but that's what happens when you code tired! I'll add a changelog, but that's the changes, just as an fyi.
