### ISSUE TITLE
limit_to_screen property is not honored on initial load and when new boxes are added.

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [BTMorton/angular2-grid#199]
This can be replicated on the live demo application on chrome or safari on mac(only browsers i tested) when loaded or when a new box is added, do not honor the limit_to_screen property. however when i resize the window the boxes reposition into multiple rows. 

to replicate the issue doing the following should help:
increase the default number for boxes loaded.
changing 'cascade' property to left. 

<img width="1351" alt="screen shot 2017-02-08 at 5 25 09 pm" src="https://cloud.githubusercontent.com/assets/8475374/22760245/a3f9c886-ee23-11e6-885f-7d74e6507535.png">

it would be great if there is a way to limit the number of boxed per row based on the device break points  allowing the boxes to flex on larger devices. 

regards,
--Rajesh.

**Comment by BTMorton** [comment]
Closed in 7a538f3d9bfa731e55d8f1ac8b973095e7246040
