### ISSUE TITLE
NgGrid: _dragStart-> getItemFromPosition returns null

### ISSUE THREAD

**Issue by Franki1986** [BTMorton/angular2-grid#208]
I had situations where getItemFromPosition returns null. 
The method _dragStart does not look at this and throws an error.

You have to do a null check in there...

**Comment by jossai1** [comment]
I have the same problem. This is what i get


![](https://cloud.githubusercontent.com/assets/9076124/23579200/35dd0bc2-00e0-11e7-8a20-834e35b23bb4.png)
