### ISSUE TITLE
Remove items from grid

### ISSUE THREAD

**Issue by Aides359** [BTMorton/angular2-grid#215]
As far as I see there is no public API to remove items.

https://github.com/BTMorton/angular2-grid/blob/master/src/directives/NgGrid.ts#L354 presents a public removeItem function, however I see no way to access it from the template or component using the directive (especially with removeItem requiring a reference to the GridItem).

Removing items from the bound item collection using `items.splice(x, 1)` causes really weird behaviour (items are being duplicated, wrong item is deleted, ...).

On side note: if the direcives used `@Directive({ selector='[ngGrid]', exportAs='ngGrid' })` and `@Directive({ selector='[ngGridItem]', exportAs='ngGridItem' })` we could probably at least do something like
```
<div #grid [ngGrid]="gridconfig">
    <div #gridItem *ngFor="let item of itemconfig; let i = index" [(ngGridItem)]="itemconfig[i]">
        <button (click)="grid.removeItem(gridItem)">Remove</button>
    </div>
</div>
```

**Comment by Aides359** [comment]
To be more concrete on the "weird behaviour":
With
```
0|1|2
3|4|5
6|7

Delete 1

0|4|2
3|4|5
6|7
-|7
```
all items cascading up are duplicated.

**Comment by BTMorton** [comment]
So, you shouldn't need to call the `removeItem` method at all. When you remove the item from the array that is bound to the ngFor, it should remove the item from the grid automatically.

**Comment by Aides359** [comment]
Yes, I did realize that after looking at the example and fixing the bug described above (gonna file a seperate issue for that).
