### ISSUE TITLE
Can't bind to 'ngGrid' 

### ISSUE THREAD

**Issue by ybensacq** [BTMorton/angular2-grid#216]
Hello I have the following error 

> Can't

 bind to 'ngGrid' since it isn't a known property of 'div'. ("

find my package.json

`{
  "name": "inspinia",
  "version": "2.7.0",
  "license": "Wrapbootstrap",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.9",
    "@angular/compiler": "~2.4.*",
    "@angular/compiler-cli": "~2.4.*",
    "@angular/core": "~2.4.*",
    "@angular/forms": "~2.4.*",
    "@angular/http": "~2.4.*",
    "@angular/platform-browser": "^2.4.9",
    "@angular/platform-browser-dynamic": "~2.4.*",
    "@angular/router": "^3.4.9",
    "angular2-jwt": "^0.1.28",
    "animate.css": "3.1.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.1.0",
    "metismenu": "^2.5.0",
    "rxjs": "^5.2.0",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.7"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-beta.32.3",
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "codelyzer": "1.0.0-beta.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.1.6"
  }
}
`

do you see any problem?

**Comment by BTMorton** [comment]
Have you included the `NgGridModule` in your app's module? That and set up the system.js config links? Are you using a regular Angular 2 app or the angular cli setup?

**Comment by ybensacq** [comment]
yes its included, I use the cli setup

**Comment by shadymostafa** [comment]
@ybensacq did you find a solution?

**Comment by ybensacq** [comment]
@shadymostafa yes but I dont remember if the problem was on my side.
