### ISSUE TITLE
NgGridConfig

### ISSUE THREAD

**Issue by aitipi22** [BTMorton/angular2-grid#221]
I have created a table in my database with NgGridConfig interface properties but I am not able to subscribe on its values. For NgGridItemConfig I am able to subscribe in its values.

  I need some help

**Comment by OnlyAGhost** [comment]
Do you have any samples of what you are trying to do?

**Comment by aitipi22** [comment]
I fixed the problem . Thank you for your comment. I have another open issue. Can you please take a look?
