### ISSUE TITLE
Using dragHandle in firefox causes error

### ISSUE THREAD

**Issue by lkirby1266** [BTMorton/angular2-grid#225]
We've been using the angular2-grid for a little while now and are generally happy with it.  On Firefox 52.0.2 (64-bit) we get the error below in the console when we specify an element selector as the dragHandle.  Not sure of the specifics that cause the issue and it does not seem to be a problem in Chrome.  The NgGridItem that causes the error most frequently houses an angular2-calendar that is loaded with events.  It seems to happen intermittently as a result of hovering over an event in the calendar although there may be other causes as well.  We found that adding a try/catch block to the findHandle() method improves the behavior but may not address the root cause:

    NgGridItem.prototype.findHandle = function (handleSelector, startElement) {
        try {
            var targetElem = startElement;
            while (targetElem && targetElem != this._ngEl.nativeElement) {
                if (this.elementMatches(targetElem, handleSelector))
                    return true;
                targetElem = targetElem.parentElement;
            }
         } catch(err) {}
        return false;
    };

ERROR TypeError: null has no properties
Stack trace:
NgGridItem.prototype.elementMatches@http://localhost:4200/vendor.bundle.js:108920:13
NgGridItem.prototype.findHandle@http://localhost:4200/vendor.bundle.js:108661:21
NgGridItem.prototype.canDrag@http://localhost:4200/vendor.bundle.js:108653:20
NgGridItem.prototype.onMouseMove@http://localhost:4200/vendor.bundle.js:108701:53
NgGrid.prototype.mouseMoveEventHandler@http://localhost:4200/vendor.bundle.js:61917:17
View_DesktopComponent_0/<@ ng:///AppModule/DesktopComponent.ngfactory.js:128:21
viewDef/handleEvent@http://localhost:4200/vendor.bundle.js:12064:94
callWithDebugContext@http://localhost:4200/vendor.bundle.js:13272:39
debugHandleEvent@http://localhost:4200/vendor.bundle.js:12860:12
dispatchEvent@http://localhost:4200/vendor.bundle.js:9042:12
renderEventHandlerClosure/<@http://localhost:4200/vendor.bundle.js:9631:38
decoratePreventDefault/<@http://localhost:4200/vendor.bundle.js:29959:53
ZoneDelegate.prototype.invokeTask@http://localhost:4200/vendor.bundle.js:151381:17
NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onInvokeTask@http://localhost:4200/vendor.bundle.js:4348:28
ZoneDelegate.prototype.invokeTask@http://localhost:4200/vendor.bundle.js:151380:17
Zone.prototype.runTask@http://localhost:4200/vendor.bundle.js:151180:28
ZoneTask/this.invoke@http://localhost:4200/vendor.bundle.js:151434:28
  DesktopComponent.ngfactory.js:50:6
ERROR CONTEXT Object { view: Object, nodeIndex: 1, nodeDef: Object, elDef: Object, elView: Object }  DesktopComponent.ngfactory.js:50:6
	View_DesktopComponent_0 ng:///AppModule/DesktopComponent.ngfactory.js:50:6
	CompileMetadataResolver.prototype._createProxyClass/proxyClass http://localhost:4200/vendor.bundle.js:86366:20
	DebugContext_.prototype.logError http://localhost:4200/vendor.bundle.js:13212:9
	ErrorHandler.prototype.handleError http://localhost:4200/vendor.bundle.js:1362:13
	PlatformRef_.prototype._bootstrapModuleFactoryWithZone/</<.next http://localhost:4200/vendor.bundle.js:4986:65
	EventEmitter.prototype.subscribe/schedulerFn< http://localhost:4200/vendor.bundle.js:4060:36
	SafeSubscriber.prototype.__tryOrUnsub http://localhost:4200/vendor.bundle.js:19040:13
	SafeSubscriber.prototype.next http://localhost:4200/vendor.bundle.js:18989:17
	Subscriber.prototype._next http://localhost:4200/vendor.bundle.js:18931:9
	Subscriber.prototype.next http://localhost:4200/vendor.bundle.js:18895:13
	Subject.prototype.next http://localhost:4200/vendor.bundle.js:19526:17
	EventEmitter.prototype.emit http://localhost:4200/vendor.bundle.js:4046:54
	NgZone.prototype.triggerError http://localhost:4200/vendor.bundle.js:4417:56
	NgZone.prototype.forkInnerZoneWithAngularBehavior/this.inner<.onHandleError http://localhost:4200/vendor.bundle.js:4378:17
	ZoneDelegate.prototype.handleError http://localhost:4200/vendor.bundle.js:151352:17
	Zone.prototype.runTask http://localhost:4200/vendor.bundle.js:151183:25
	ZoneTask/this.invoke

**Comment by BTMorton** [comment]
Are you able to reproduce this in a plunker example? I've made a starter here you can use, if it helps: https://plnkr.co/edit/3m8ost

**Comment by ng** [comment]
plz remove me from cc. Tnx

**Comment by lkirby1266** [comment]
My firefox is now 53.0.2 (64-bit) running on Centos.  I added an angular-calendar widget to one of the NgGridItems in the plunker you supplied.  I added 40 events to the calendar.  If I hover over the events quickly moving he mouse around.  Eventually, I get the error, although the stack trace is a little shorter (maybe plunker limits the stack trace output).

**Comment by BTMorton** [comment]
Can you save and provide me a link to your updated plunker?

**Comment by ng** [comment]
<img width="456" alt="yun" src="https://cloud.githubusercontent.com/assets/47024/25862791/2a24f668-349e-11e7-90d3-eaafe89b51d6.png">

**Comment by lkirby1266** [comment]
Sorry.  New to the angular an plunker scene.  https://plnkr.co/edit/gLEM6wmaGNsDB16SdOe6?p=preview

**Comment by BTMorton** [comment]
Try/catch added in v2.0.4
