### ISSUE TITLE
Compatibility with Angular 4

### ISSUE THREAD

**Issue by Aides359** [BTMorton/angular2-grid#235]
How does this lib work with Angular 4. 
When upgrading I get peer dependency errors (similar to #173)

Also somewhat related: #232

**Comment by kladier** [comment]
I use this library with angular 4 and I got no problem

**Comment by MaGnaL** [comment]
Same here. Using it with Angular 4.2.0-rc.1 and it works.

**Comment by anthonydresser** [comment]
At run time is seems to work, however if you try and shrinkwrap with angular 4 you will get errors since angular2-grid specifically wants angular. I forked the repo and updated the dependencies to angular4 and it works as expected.

**Comment by kladier** [comment]
Make a pull request maybe ?

**Comment by anthonydresser** [comment]
Sure, I've been using it to make sure its actually stable. However, @BTMorton will probably need to make a choice if the repo should actually move to angular4 rather than just supporting it as a dependency (requiring 4 rather than requiring > 2.4, I did the former)

**Comment by BTMorton** [comment]
I've updated to accept versions `>=2 <=4` in v2.0.5
