### ISSUE TITLE
Add option to allow item overlaps

### ISSUE THREAD

**Issue by webcat12345** [BTMorton/angular2-grid#238]
Currently, if we drag widget to other then it pushed other widget. There could be an option to allow overlaps.

_**Gitter history**_: 

- webcat_black @webcat12345 15:48
I am building this using angular2-grid, and I have to implement overlap feature, any possibility?

- Ben Morton @BTMorton 15:49
It should definitely be possible with a config option, and then just ignoring call to fixGridCollisions or whatever it's called

- webcat_black @webcat12345 15:50
Thanks for your super fast response!

- Ben Morton @BTMorton 15:50
the main issue, I guess, would be with figuring out which should be on top, in which case you'd have to add some kind of zpos

- webcat_black @webcat12345 15:50
Yes. Which one should be top.... this problem could be solved by activa state I made.

- Ben Morton @BTMorton 15:52
yeah, you could just do a [attr.style]="'z-index: '+state" or similar. Feel free to re-open the issue and title it something like "Add option to allow item overlaps". I guess you'd also have to fix it to cascade: off

**Comment by webcat12345** [comment]
![image](https://cloud.githubusercontent.com/assets/19761422/26587598/0e8a06b2-4553-11e7-90cb-dda77f7ecbdb.png)

I hope this will help you to little.
Actually, I disabled these line inside node_modules directory.
`node_modules/angular2-grid/directives/NgGrid.js`

![image](https://cloud.githubusercontent.com/assets/19761422/26587791/a3c25f7c-4553-11e7-8d8d-de7936369b82.png)

Also same on _resizeStop event.

**Comment by arupalan** [comment]
added feature gridItem overlap.
By default this feature is disabled.
This can be enabled by setting 'allow_overlap': true in NgGridConfig.

Please see pull request.

**Comment by BTMorton** [comment]
This feature has been added to v2.3.0
