### ISSUE TITLE
Support maxCol / maxRow simulatenously

### ISSUE THREAD

**Issue by jpsfs** [BTMorton/angular2-grid#250]
Hi!

Is there a reason why max_cols and max_rows are not supported simultaneously?
I was hoping to achieve a similar result to:

![image](https://user-images.githubusercontent.com/1041209/27863666-1e563876-6183-11e7-9e27-7e766fafaec1.png)

Best,

**Comment by BTMorton** [comment]
Yes. By applying both max cols and max rows, it would then require lots of extra logic to figure out whether an item can still fit in the grid when it is added. The same result can be achieved by using `max_cols` and `visible_rows` which applies the same resizing logic, without adding any limitations to the number of items in the grid.

**Comment by jpsfs** [comment]
Hi @BTMorton,

Thanks for the reply!
I see you point.

We have tried to use visible_rows but it seems that the calculation is being done take the window as basis and in our case the grid doesn't occupy the entire screen (as it happens on your own example). Would you accept a PR where we would use ```elementRef.nativeElement``` instead of window?

Best,
José

**Comment by BTMorton** [comment]
Yes, I can't see there being too much issue with that

**Comment by BTMorton** [comment]
OK, I have added a new config property `element_based_row_height` which allows you to enable using the native element to calculate the visible row. It also no longer overrides the height with the max row as it assumes you are setting that yourself. Apologies this took so long to get to.
