### ISSUE TITLE
Unable to change columns size its either 250px or 520px and use resizeHandler

### ISSUE THREAD

**Issue by robertbarron** [BTMorton/angular2-grid#252]
I am unable to change the size of the columns doesn't matter the settings I add. I am currently adding dynamic components, so the module is imported to my main module, then on my components I just import the NgGridItemConfig and NgGridConfig. I can use the grid and some of the functions. but not completely and can't adjust the size of the column.

Also, I am unable to use the resizeHandler, but the moveHandler works like a charm. Any thoughts?

Here's my gridConfig and gridItemconfig:

grid:
private gridConfig: NgGridConfig = <NgGridConfig> {
    margins: [5],
    draggable: true,
    resizable: true,
    max_cols: 0,
    max_rows: 0,
    visible_cols: 0,
    visible_rows: 0,
    min_cols: 0,
    min_rows: 0,
    col_width: 300,
    row_height: 300,
    cascade: 'up',
    min_width: 100,
    min_height: 100, 
    fix_to_grid: false,
    auto_style: false,
    auto_resize: false,
    maintain_ratio: false,
    prefer_new: false,
    limit_to_screen: true,
    zoom_on_drag: true,
  };

gridItem:

 private widgetConfig: NgGridItemConfig = <NgGridItemConfig> {
    minWidth: 270,
    minHeight: 270,
    resizeHandle: '.resizeHandler',
    dragHandle: '.dragHandler',    
    fixed: false,
  };

**Comment by BTMorton** [comment]
Hmmm, interesting problem. Can you create a plunker to reproduce this at all?

**Comment by robertbarron** [comment]
I think you can close this.  I think the col_width was affecting my configuration. Changed it to 50 and set the griditemconfig as sizex and sizey. Now its working. Thank you!
