### ISSUE TITLE
Unable to build angular 4 application "main.js has no static exports true"

### ISSUE THREAD

**Issue by ajinkyau** [BTMorton/angular2-grid#254]
Hi,

I am trying to build my angular 4 application using "ng build --prod --no-aot" and getting error for angular2-grid which says:
"**node_modules\angular2-grid\main.js has no static exports true**"

I have updated the package to version "2.0.6" but still the issue persists.

This works with "ng serve".
The prod build is created successfully without using "--no-aot" flag.
But, error occurs only when I am trying to create a prod build with "--no-aot" flag.

Seems like an issue when compiling with "Jit Compiler".

**Comment by BTMorton** [comment]
Have tested the demo project with `ng build`, `ng build --no-aot`, `ng build --prod`, and `ng build --prod --no-aot` using v2.0.7 and they're all working. Thanks @borgitas21 for the fix.
