### ISSUE TITLE
Free mode without cascading?

### ISSUE THREAD

**Issue by avatsaev** [BTMorton/angular2-grid#266]
Is there a way to use the grid without any cascading? ('cascade': 'left'/right/etc), so I can place my widgets wherever I want vertically or horizontally (without them automatically sticking to the borders)?

**Comment by BTMorton** [comment]
Yes, if you set the cascade value to anything other than those values, it will disable the cascade. In the demo example, you can use the "Off" setting to try it out.

**Comment by avatsaev** [comment]
I'm an idiot, thank you.
