### ISSUE TITLE
How can I prevent grid from updating?

### ISSUE THREAD

**Issue by maxmedina05** [BTMorton/angular2-grid#269]
I want to prevent the grid from updating while I drag on top of other grid items.
I want to update the grid only when I drop the item.

**Comment by BTMorton** [comment]
Currently, that's not possible. If I were to add this as a feature, how would you expect it to behave? For example, should the placeholder appear over the top of whichever element is currently in the drop target location, or just not be there at all?

**Comment by maxmedina05** [comment]
It's okay, I solved my issue by removing the Cascade. After that I get the behavior I wanted

**Comment by maxmedina05** [comment]
It's okay, I solved my issue by removing the Cascade. After that I get the behavior I wanted
