### ISSUE TITLE
Doesn't work with latest angular cli 1.1.2

### ISSUE THREAD

**Issue by RaedsLab** [BTMorton/angular2-grid#272]
```html
<div [ngGrid]="{'resizeable': false, 'margins': [5, 10]}">
    <div *ngFor="let box of boxes" [(ngGridItem)]="box.config">
        <div class="title">{{box.title}}</div>
        <p>{{box.text}}</p>
    </div>
</div>
```

> Can't bind to 'ngGrid' since it isn't a known property of 'div'.

I think this is because Angular got rid of System.js

**Comment by BTMorton** [comment]
What's the rest of your config look like? My demo is running using the cli without issue. I'll make sure it's up to date. Have you included the NgGridModule in your app's NgModule? If you have and it's compiling correctly, I can't see why you'd get this issue
