### ISSUE TITLE
is this the alternative of isotope or masonry ?

### ISSUE THREAD

**Issue by saifulazad** [BTMorton/angular2-grid#276]
I have seen isotope and masonry. Can I use this Module as the alternative of those? 
**Maybe this is not appropriate place to ask this.**

**Comment by BTMorton** [comment]
This is more of a replacement to [gridster](http://dsmorse.github.io/gridster.js/) or [packery](https://packery.metafizzy.co/), though with different algorithms for calculating box/item layouts
