### ISSUE TITLE
Grid Item events

### ISSUE THREAD

**Issue by pocmanu** [BTMorton/angular2-grid#28]
Hello,
Thanks for this great NgGrid, I've started playing with it but met a problem when trying to listen for individual item events.

Using something like this :
```html
    <div *ng-for="#box of boxes" 
         (dragStart)="log('dragStart')" 
         (drag)="log('drag')" 
         (dragStop)="log('dragStop')" 
         (resizeStart)="log('resizeStart')" 
         (resize)="log('resize')" 
         (resizeStop)="log('resizeStop')" 
         (itemChange)="log('itemChange')" 
         [ng-grid-item]="{'col':1, 'row':4, 'sizex': 1, 'sizey':3, 'dragHandle':'.title'}">
```
only brings me 'drag' and 'resize' events.

Maybe because they're called by the mother grid 
```javascript
			this.resize.next(this._resizingItem);
			this._resizingItem.resize.next(this._resizingItem.getDimensions());
```

whereas the others are not ?

Or am I doing something wrong ?

Thanks for the time.

**Comment by BTMorton** [comment]
Hmmm. They should definitely be getting called from the main grid.

```
			this.dragStart.next(item);
			item.dragStart.next(item.getPosition());
...
			this.resizeStart.next(item);
			item.resizeStart.next(item.getDimensions());
```

I'll investigate and see if I can replicate it.

**Comment by pocmanu** [comment]
Indeed, only the itemChange is called internally by the grid-item itself.

**Comment by BTMorton** [comment]
Ah, yes... s/camel/_/

Angular uses camelCase for it's event names and underscores for event bindings. You should be listening on (resize-start) etc.

**Comment by pocmanu** [comment]
Ah... indeed, forgot that, sorry for that, it works fine with 'item-change'
