### ISSUE TITLE
Problem config System js Angular 4

### ISSUE THREAD

**Issue by habella** [BTMorton/angular2-grid#281]
**Error =>:  No provider for NgGrid!** 

**Systemjs**
```
map: {
    'angular4-grid': 'node_modules/angular4-grid/bundles'
}

packages: {
    'angular4-grid': { main: 'NgGrid.umd.js',  defaultExtension: 'js' }
}

```

**Module**

    import { NgGridModule } from 'angular4-grid';
    @NgModule({
      imports: [
       ...
        NgGridModule
       ...
      ]
      providers:[]
    })

**Comment by BTMorton** [comment]
The library is still called "angular2-grid", despite you using angular 4. Unless someone else has published it under a different name, that is. You want your import to be:
```
import { NgGridModule } from 'angular2-grid';
```
and the System.js config:
```
map: {
    'angular2-grid': 'node_modules/angular2-grid/bundles'
}

packages: {
    'angular2-grid': { main: 'NgGrid.umd.js',  defaultExtension: 'js' }
}
```
