### ISSUE TITLE
No cascading

### ISSUE THREAD

**Issue by pocmanu** [BTMorton/angular2-grid#29]
Hi, me again.

In my use case, I'd like to freely place my items in any cell of the grid (eg : x = 10, y= 10). I tried to set 'cascade' : 'null' and it worked pretty well until I had more than 1 box.

Having 2 boxes leads to complete tab freeze when dragging a box on another one.

From what I understand of your code, I don't think it has been designed to work in this free placing mode but it seems to be quite close to have it work. I'm not sure of the mechanic, do you think it would be feasible ?

**Comment by BTMorton** [comment]
Was a relatively simple fix. The _fixGridCollisions function was endlessly looping as it didn't have a method to fix the collision. Have added a default and disabled it from being run during the drag if there isn't a valid cascade set. That should fix your issue. You can see it working on the demo page. Feel free to re-open if it doesn't solve your issue :P

**Comment by pocmanu** [comment]
Issue solved, nice work :)
