### ISSUE TITLE
Compatibility with Angular 5

### ISSUE THREAD

**Issue by Smitha-Patil** [BTMorton/angular2-grid#292]
Does this library work for Angular 5? We are really looking forward to using it.

**Comment by BTMorton** [comment]
Yes, this library will work fine with Angular v2 through v5. Support for v6 is in the works and I'm planning to incorporate the angular2-grid-demo project as well, using the cli library support.

**Comment by Smitha-Patil** [comment]
Thank You. Could you please tell me the changes i need to do for angular-cli support as i do not have a system.js. I am getting an error saying ngGrid and ngGridItem is not known.

**Comment by BTMorton** [comment]
I didn't have to do anything specific to get it working. Just npm installed it and included NgGridModule in the AppModule imports.
You can see my CLI demo project here: https://github.com/BTMorton/angular2-grid-demo

It may be that the package versions are mismatched, which could cause npm dependency issues, but that shouldn't cause the issue you're seeing above.

**Comment by Smitha-Patil** [comment]
Hey, Thanks for the example. I had imported the NgGridModule in a wrong module. My mistake :).
