### ISSUE TITLE
Support for Angular 6

### ISSUE THREAD

**Issue by tzoratto** [BTMorton/angular2-grid#296]
Hello there, 

thanks for this lib and the work you put in it is really appreciated !

I was just wondering if you had planned to release the angular 6 support soon or not ?

I've seen you were working on it in https://github.com/BTMorton/angular2-grid/issues/292

**Comment by borgitas21** [comment]
#295

**Comment by endlesscadence** [comment]
@BTMorton Any update on this? 

The library is wonderful and we're using it for quite some time now but it's sad that it's broken with Angular 6. This means that we have to drop the functionality which depends on this library because we have to upgrade to Angular 6 for other reasons.

If you need help completing the PR please let me know!

**Comment by tzoratto** [comment]
Hi @endlesscadence, we also had to upgrade to Angular 6 recently and we still use this library flawlessly. To do so, you want to add the rxjs-compat package to your project.
Still, this is a temporary workaround

**Comment by endlesscadence** [comment]
Hi @tzoratto, thank you very much! Yes this works but I agree with you that this is a workaround. Also, I had to explicitly import the rxjs-compat lib in my lazy loaded module for this to work in a AoT build.

**Comment by naman1901** [comment]
Hi, I recently migrated to Angular 6 from 4 as well. After the upgrade, the positioning and resizing don't work like intended. I had asked this question at StackOverflow as well [here](https://stackoverflow.com/questions/52700405/alternatives-to-or-suggestion-on-how-to-make-work-angular2-grid-in-angular-6?noredirect=1#comment92327674_52700405).

I have rxjs-compat installed, but I am still facing this issue.

**Comment by naman1901** [comment]
@endlesscadence how exactly do you import the lib into a lazy-loaded module?

**Comment by naman1901** [comment]
@endlesscadence  @tzoratto was your issue a failing build or was it about some functionality not working as expected?

**Comment by tzoratto** [comment]
IIRC, it was a failing build, because of the breaking changes in rxjs API in version 6 (hence the need for rxjs-compat which "restore" the previous API)

**Comment by naman1901** [comment]
Alright, thanks! In my case it is a behaviour issue after the migration. rxjs-compat was automatically installed when I upgraded according to the Angular guide.

**Comment by avatsaev** [comment]
Any news on this? I'm getting a lot of rxjs errors on 6 and 7, 

```
TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_1__.Observable.fromEvent is not a function

```

The `angular6` branch isn't merged yet? what's missing?

**Comment by BenBruda** [comment]
@avatsaev 
It seems with `rxjs-compat: 6.2.2` it works, but from `6.3.3` it **doesn't** any more.

**Comment by tzoratto** [comment]
maintener seems to be off the grid (sorry about this one :joy: ), this is really embarrassing, maybe we should consider forking

**Comment by BTMorton** [comment]
v3.0.0 just published with angular 6 support. Sorry it took so long!

**Comment by tzoratto** [comment]
that's really good news, we can finally drop rxjs-compat thanks @BTMorton !

What's the plan regarding Angular 7 ? It works fine with it but still produces a warning on npm install ;)

By the way, the changelog misses the 3.0.0 part

thanks for your work
