### ISSUE TITLE
Should we expect support for Angular 8? When?

### ISSUE THREAD

**Issue by RaSMiY** [BTMorton/angular2-grid#304]

**Comment by yarkopro** [comment]
Any updates there?

**Comment by webcat12345** [comment]
Angular 9 is released and Renderer is finally removed. It means we can't use this library with Angular 9 anymore...

**Comment by webcat12345** [comment]
Here is my PR. Could you please review this @BTMorton ?
https://github.com/BTMorton/angular2-grid/pull/305

**Comment by BTMorton** [comment]
Version 4.0.0 should support v8 and v9
