### ISSUE TITLE
Make readmy more novice-friendly

### ISSUE THREAD

**Issue by lifecoderua** [BTMorton/angular2-grid#35]
I am new to angular 2 and typescript, and struggling to include angular2-grid.

It shouldn't be an issue after some time but for the moment a lot would struggle on this I guess. `.ts` component sample would be extremely helpful.

I am able to include it with

``` js
import {NgGrid, NgGridItem} from '/node_modules/angular2-grid/dist/NgGrid.js';

@Component({
    directives: [NgGrid, NgGridItem],
```

but the full path feels weird. I thought `angular2-grid` is a correct way — but it doesn't work (trying to fetch `/angular2-grid` in runtime and fails).

TS event handling example would also help a lot.

**Comment by BTMorton** [comment]
Have you tried doing

``` typescript
import { NgGrid } from 'NgGrid';
```

Instead of angular2-grid?

**Comment by lifecoderua** [comment]
``` ts
import {NgGrid, NgGridItem} from 'NgGrid';
```

```
# browser console
Uncaught SyntaxError: Unexpected token <
	Evaluating http://localhost:4567/NgGrid 
	Error loading http://localhost:4567/app/boot.js
```
The app is based on the "5 min quickstart", on NgGrid import it tries to load NgGrid by relative path.

In case I'm adding 
``` <script src="node_modules/angular2-grid/dist/NgGrid.js"></script> ``` to the page I got 
``` Uncaught ReferenceError: require is not defined (NgGrid.ts:1)``` — no idea why **.ts** here.

**Comment by BTMorton** [comment]
Hmm ok, I'll have a go at replicating it either later today or tomorrow. I think it might be that my .js output isn't in system format, which will need updating.

It says .ts there because I've enabled source maps for the compiler. So that when you inspect issues with the .js file, it will show you the TypeScript rather than native JS.

**Comment by lifecoderua** [comment]
Thank you. I have to add I'm not that cool with the stack and it could be  an issue on my app side.

**Comment by BTMorton** [comment]
There's definitely a compiler change to be made there. It should be `module: "system"` not `module: "common"` in the TS config so I'll change that. I think with that change, including the file directly will solve it as it'll be loaded by System.js correctly.

**Comment by dy0nysos** [comment]
I'm experiencing this issue too and was wondering if using require.js would fix (temporary) the issue ?

**Comment by BTMorton** [comment]
OK, give that one a go guys :)

**Comment by BTMorton** [comment]
OK, I've made a demo project that is viewable at http://bmorton.co.uk/angular_test/ and in the demo/ folder. I realised a few issues with the package config and bits and bobs. This should resolve all your issues!
