### ISSUE TITLE
Add col/row information to drag* events 

### ISSUE THREAD

**Issue by lifecoderua** [BTMorton/angular2-grid#37]
It is very likely scenario when a user moves items to change their personal info only, and uses columns/rows as states or something. In this case `col` and `row` data is much more useful than offsets.

While itemChange passes that info, it fires for every change (not only dragStop), and every element involved (not only the dragged one).

**Comment by BTMorton** [comment]
Do you think we should do:

```javascript
dragStop({'left': number, 'top': number, 'col': number, 'row': number})
```
or 
```javascript
dragStop({'position': {'col': number, 'row': number}, 'offset': {'left': number, 'top': number} })
```

I imagine the first one would be easier to use, but could possibly cause some confusion?

**Comment by lifecoderua** [comment]
I guess it should return common informational object for any event. 

`dragStop({'left': number, 'top': number, 'col': number, 'row': number})` looks better for me. Also not sure if offsets are useful (and if they are - it may be better to provide DOM element link instead to cover other element specific properties as well)

**Comment by BTMorton** [comment]
My original thinking for it was if someone wanted to use the current mouse/box position during the drag and overlay or output something using that data. But I can add the col/row values without much extra work
