### ISSUE TITLE
NgGridItem positioning config fails

### ISSUE THREAD

**Issue by lifecoderua** [BTMorton/angular2-grid#39]
`<div *ngFor="#box of boxes" [ngGridItem]="{'dragHandle': '.title', 'col': box.col, 'row': 1}" (dragStop)="onDrag(box, $event)">`

```
boxes = [
        {title: '0AAA', text: 'lorem ipsum', col:3},
        {title: '1AAA', text: 'lorem ipsum', col:3},
        {title: '2AAA', text: 'lorem ipsum', col:1},
        {title: '3AAA', text: 'lorem ipsum', col:1},
        {title: '4AAA', text: 'lorem ipsum', col: 2}
    ];
```

Result:
- **0AAA** at column 3
- **1AAA** at column **4**, expected: col 3 row 2
- **2AAA** at column 1
- **3AAA** at column **2**, expected: col 1 row 2
- **4AAA** at column **5**, expected column 2

**Comment by lifecoderua** [comment]
With rows specified in addition to columns it works as expected, but this means user have to track each row current capacity

**Comment by BTMorton** [comment]
It's because the function that adds items to the grid currently doesn't take into account the cascade direction and moves all items along by one column. I'll sort it at some point :)

**Comment by lifecoderua** [comment]
I'm not sure it is exactly tied with cascade.For example I'm free to init an item on col:4 row:2, even if the col:4 row:1 is empty. And this item will be there, until something got moved (then it would be pushed up by default cascade).

**Comment by BTMorton** [comment]
Yeah, I mean the function _fixGridPosition doesn't take into account any of the cascade stuff. It's been around since I began working on the grid and needs a little love
