### ISSUE TITLE
version 0.4.1 from npm looks like dist was not compiled from src?

### ISSUE THREAD

**Issue by roddym** [BTMorton/angular2-grid#41]
In src/NgGrid.ts I see
	public ngOnInit(): void {
In dist/NgGrid.js I see
                NgGrid.prototype.ngOnInit = function (_ngEl) {
And in dist/NgGrid.d.ts I see
    ngOnInit(_ngEl: ElementRef): void;

Which I think upsets my compile:
node_modules/angular2-grid/dist/NgGrid.d.ts(2,22): error TS2420: Class 'NgGrid' incorrectly implements interface 'OnInit'.
  Types of property 'ngOnInit' are incompatible.
    Type '(_ngEl: ElementRef) => void' is not assignable to type '() => any'.

Apologies if this is a newbie angular2, typescript question

**Comment by BTMorton** [comment]
Yes... I made a fuck up, my bad. Fixed in version 0.4.2 :)
