### ISSUE TITLE
Add clone option 

### ISSUE THREAD

**Issue by behzad888** [BTMorton/angular2-grid#42]
Hi,
How can I select the cloned object? 
Is there any internal function for it?

**Comment by BTMorton** [comment]
I'm not entirely sure what you mean... What exactly do you want to be able to clone?

**Comment by TheBolmanator** [comment]
Hello Ben, great work!  I wouldn't want to speak for behzad, but let me respond with a 'yes' I would like to be able to clone.  

I am looking to develop something like [https://polymer-designer](url) https://polymer-designer.appspot.com/ (which is great but built on the older Angular).  If you visit this site you will see a "Pallet" where elements can be dragged onto a grid (not certain if it is technically a 'grid' in the sense of your grid) by clicking on a 'psudo button' and dragging and dropping an object emitted by the click/tap event on the Pallet.  (easiest to visit the site to see what I mean).

**Comment by BTMorton** [comment]
Yeah, that's a similar grid system, if you set the width/height of the cols/rows of mine to be that small. You can definitely do cloning of the items on the grid, but that's not part of the grid itself. The grid/items are just directives on the components and don't have any impact on the component themselves. If you want to be able to 'clone' an item, you clone the component and just add the new element to the grid. Does that make sense?

Taking from your example website, possibly something I could add is the ability to set z-indexes and to disable both cascading and collision detection. But cloning, in my opinion, is beyond the scope of what the grid should do.

**Comment by TheBolmanator** [comment]
Got it many thanks.  So your grid is something completely independent from something like the "Dragula" project [https://github.com/bevacqua/dragula](url), if you agree and do not anticipate collisions, this closes out my question comment, again many thanks.

Steve

**Comment by BTMorton** [comment]
@TheBolmanator You could use Dragula inside of a component within the grid, sure, as long as you set up your drag handles correctly. You may find some collisions depending on how you configure things. Obviously, I don't know what you're aiming to do with them so I can't say for definite how they'll work together, unfortunately. But this project is closer to something like [Gridster](http://gridster.net/)

**Comment by TheBolmanator** [comment]
Ben,
Many thanks for the Gridster tip.  This is a huge help, and you were
absolutely correct that this is more aligned with what I was looking for.

Again many thanks,
Steve

On Mon, Feb 1, 2016 at 7:27 AM, Ben Morton <notifications@github.com> wrote:

> @TheBolmanator <https://github.com/TheBolmanator> You could use Dragula
> inside of a component within the grid, sure, as long as you set up your
> drag handles correctly. You may find some collisions depending on how you
> configure things. Obviously, I don't know what you're aiming to do with
> them so I can't say for definite how they'll work together, unfortunately.
> But this project is closer to something like Gridster
> <http://gridster.net/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTMorton/angular2-grid/issues/42#issuecomment-177971257>
> .
>



-- 
Steve Bolman
Cell - (832) 326-8984
