### ISSUE TITLE
EXCEPTION: TypeError: Cannot set property 'width' of undefined in [gridConfig in SpeedDialsCmp@1:5]

### ISSUE THREAD

**Issue by kjensenportfolio** [BTMorton/angular2-grid#44]
I have put the basic grid in, but I am getting an error

EXCEPTION: TypeError: Cannot set property 'width' of undefined in [gridConfig in SampleGridCmp@1:5]

The code looks pretty much the same as the src app.ts code that is in the angular2-grid repo. And the error comes up when the page is resized. it seems to be logged in the browser_adapter.ts file in Angular2

*****  > sanple.html

<div [ngGrid]="gridConfig">
  <div *ngFor="#box of boxes" [ngGridItem]="{'dragHandle': '.title'}">
    <div class="title">{{box.title}}</div>
    <p>{{box.text}}</p>
  </div>
</div>

*****  > sample.ts

/**
 * Created by Administrator on 12/5/15.
 */
import {
  Component,
  View,
  ViewEncapsulation
  //enableProdMode
}
  from 'angular2/core';
import {
  CORE_DIRECTIVES,
  NgStyle,
  FORM_DIRECTIVES
}
  from 'angular2/common';
import {
  NgGrid,
  NgGridItem
}
//  from 'angular2-grid';
  from 'angular2-grid/dist/NgGrid';

@Component({
  selector: 'speeddials'

})

@View({
  templateUrl: './sample/components/sample.html',
  styleUrls: ['./sample/components/sample.css'],
  directives: [CORE_DIRECTIVES, NgStyle, NgGrid, NgGridItem, FORM_DIRECTIVES],
  encapsulation: ViewEncapsulation.None

})

export class SampleGridCmp {

  private boxes = [1, 2, 3, 4];
  private rgb = '#efefef';
  private curNum: number = 5;
  private gridConfig = {
    'margins': [5],
    'draggable': true,
    'resizable': true,
    'max_cols': 6,
    'max_rows': 0,
    'min_cols': 1,
    'min_rows': 1,
    'col_width': 250,
    'row_height': 250,
    'cascade': 'up',
    'min_width': 100,
    'min_height': 100,
    'fix_to_grid': false,
    'auto_style': true,
    'auto_resize': true
  };
  private curItem = {
    'col': 0,
    'row': 0,
    'sizex': 0,
    'sizey': 0
  };
  private curItemCheck: number = 0;
  private itemPositions: Array < any > = [];

  get itemCheck() {
    return this.curItemCheck;
  }
  set itemCheck(v: number) {
    this.curItem = this.itemPositions[v];
    this.curItemCheck = v;
  }

  addBox() {
    this.boxes.push(this.curNum++);
  }

  removeBox() {
    if (this.boxes[this.curItemCheck]) this.boxes.splice(this.curItemCheck, 1);
  }

  updateItem(index: number, pos: {
    col: number,
    row: number,
    sizex: number,
    sizey: number
  }) {
    this.itemPositions[index] = pos;
    if (this.curItemCheck === index) this.curItem = pos;
  }

  onDrag(index: number, pos: {
    left: number,
    top: number
  }) {
    // Do something here
  }

  onResize(index: number, dims: {
    width: number,
    height: number
  }) {
    // Do something here
  }

}

**Comment by BTMorton** [comment]
Can I see your app.html as well?

**Comment by drewlio** [comment]
Running into the same issue using 0.4.2. I made the simplest example I could:
```
import {Component} from 'angular2/core';
import {NgGrid, NgGridItem} from './NgGrid';

@Component({
    selector: 'grid-test',
    template: `
    <div [ngGrid]="{'resizeable': false, 'margins': [5, 10]}">
        <div *ngFor="#box of boxes" [ngGridItem]="{'dragHandle': '.title'}">
            <div class="title">{{box.title}}</div>
            <p>{{box.text}}</p>
        </div>
    </div>`,
    directives: [NgGrid, NgGridItem]
})
export class GridTestComponent {
    boxes = [
        {
            "title": "Title 1",
            "text": "Text 1"
        },
        {
            "title": "Title 2",
            "text": "Text 2"
        }
    ];
}
```

results in

```
EXCEPTION: TypeError: Cannot set property 'width' of undefined in [{'resizeable': false, 'margins': [5, 10]} in GridTestComponent@1:9]
```

**Comment by BTMorton** [comment]
Ahhh, I think I've found it. When the ngGridItems get created, they don't initially set the default configuration. Should (hopefully) be an easy fix. Will try and get on it ASAP. In the meanwhile, set line 986 of NgGrid.ts with:

```javascript
private _config = NgGridItem.CONST_DEFAULT_CONFIG;
```

(Not sure what line that is in the .js...)

NOTE: Untested. Just my thoughts from a quick scan of the code :P

**Comment by drewlio** [comment]
Changing line 986 seems to **not** work. No difference in the error.

Here's more error output:
```
TypeError: Cannot set property 'width' of undefined
    at BrowserDomAdapter.setStyle (angular2.js:22923)
    at DomRenderer.setElementStyle (angular2.js:13757)
    at NgGrid._updateSize (NgGrid:842)
    at NgGrid.setConfig (NgGrid:262)
    at NgGrid.Object.defineProperty.set [as config] (NgGrid:91)
    at AbstractChangeDetector.ChangeDetector_GridTestComponent_0.detectChangesInRecordsInternal (viewFactory_GridTestComponent:92)
    at AbstractChangeDetector.detectChangesInRecords (angular2.js:7825)
    at AbstractChangeDetector.runDetectChanges (angular2.js:7808)
    at AbstractChangeDetector._detectChangesInViewChildren (angular2.js:7892)
    at AbstractChangeDetector.runDetectChanges (angular2.js:7812)
```

It looks like it's related to the NgGrid (vs NgGridItem). Line 842 appears to be setting the width on `this._ngEl` within NgGrid (not NgGridItem).

**Comment by BTMorton** [comment]
Hmmm OK. Out of curiosity, what version of Angular 2 are you running? Beta 0 or 1?

**Comment by drewlio** [comment]
Beta 1.

**Comment by BTMorton** [comment]
Ah, that'll be it then. It doesn't work with beta 1 yet since they changed a whole bunch of stuff on the view front

**Comment by drewlio** [comment]
ok. What's your plan for tracking the Angular2 beta releases?

**Comment by BTMorton** [comment]
I'm trying to keep on top of them. But as with most of the updates to this, its basically just when I get a chance... Sorry I can't be more definitive

**Comment by drewlio** [comment]
Alright. I do ask that you continue to put in your release comments what Angular2 version it's targeting (like when you said 0.3.4 was for Beta 0). It's quite a nice component. Thank you for it.

**Comment by drewlio** [comment]
From the Angular2 [CHANGELOG.md](https://github.com/angular/angular/blob/master/CHANGELOG.md):

>renderer.setElementProperty, ..setElementStyle, ..setElementAttribute now take a native element instead of an ElementRef

NgGrid.ts:94, `_ngEl` is type `ElementRef`
```
constructor(private _differs: KeyValueDiffers, private _ngEl: ElementRef, private _renderer: Renderer, private _loader: DynamicComponentLoader) { }
```

NgGrid.ts:842, it's used here
```
this._renderer.setElementStyle(this._ngEl, 'width', "100%");
```

angular2/code.d.ts:6599, `ElementRef` has a `nativeElement`
```
abstract class ElementRef implements RenderElementRef {
    nativeElement: any;
    renderView: RenderViewRef; 
}
```

NgGrid.ts:842, and when we change it to this, it gets us past that one error
```
this._renderer.setElementStyle(this._ngEl.nativeElement, 'width', "100%");
```

hope this helps!

**Comment by drewlio** [comment]
Also, there seems to be some rearranging of what used to be in the `ElementRef`. You can access it at `this._ngEl.internalElement`. Looks like the first change needs to be on line 936:

NgGrid.ts:936
```
this._loader.loadNextToLocation((<Type>NgGridPlaceholder), (<any>this._ngEl).parentView._view.elementRefs[(<any>this._ngEl).boundElementIndex + 1]).then(componentRef => {
```

But I'm getting a little lost past the `.parentView`. Seems like it should be something like this (but this does not work):
```
this._loader.loadNextToLocation((<Type>NgGridPlaceholder), (<any>this._ngEl).internalElement.parentView._view.elementRefs[(<any>this._ngEl).internalElement.boundElementIndex + 1]).then(componentRef => {
```

**Comment by BTMorton** [comment]
OK, give the latest release a go :)

**Comment by drewlio** [comment]
Seems to work fine. Thank you very much!
