### ISSUE TITLE
Version on NPM doesn't work with Angular2-beta2

### ISSUE THREAD

**Issue by TopHoot** [BTMorton/angular2-grid#45]
Can you please upload your most recent changes to the version available via NPM? I would love to use  this but I need Angular-beta2

**Comment by BTMorton** [comment]
Huh, I could have sworn I already did that... Give it a try now (should be 0.4.3)

**Comment by firecube** [comment]
Version 0.4.3 on npm errors with beta3 but the ts NgGrid.ts in source works great.

**Comment by BTMorton** [comment]
OK, I've released version 0.4.4 which seems to work with beta 1 through 3. http://bmorton.co.uk/angular_test/ is currently running on beta 2 as a demo. Give it a go and see if it resolves your issues. (Sorry for the delay in responding)

**Comment by BTMorton** [comment]
Since I haven't heard otherwise, I'm going to go ahead and assume it's all working now!
