### ISSUE TITLE
Typescript compilation explanation.

### ISSUE THREAD

**Issue by daprezjer** [BTMorton/angular2-grid#46]
For those starting off w/ typescript in Angular2, would be helpful to include more details for this instruction in the readme.
"include NgGrid.ts into your typescript compilation. No more work needed!"

Would also be helpful to show an example on the README of the import line and the directives include.

**Comment by Vrael** [comment]
You can add the next lines to **typings.json** file:

```json

  "dependencies": {
    "NgGrid": "github:BTMorton/angular2-grid/src/NgGrid.d.ts"
  }

```
In [Angular 2 Quickstart](https://angular.io/docs/ts/latest/quickstart.html#typescript-typings) there are more information about this file.

**Comment by BTMorton** [comment]
You should be able to simply do:

```typescript
import { NgGrid, NgGridItem } from 'angular2_grid';
```

and then add `NgGrid` and `NgGridItem` as directives in your `@Component` annotation. Check out how it's done in the [demo project ](https://github.com/BTMorton/angular2-grid/blob/master/demo/app/app.component.ts)
