### ISSUE TITLE
try to translate cmd is not work well

### ISSUE THREAD

**Issue by HereSinceres** [BTMorton/angular2-grid#47]
npm install angular2-grid is system module, i wanner use it in webpack ，so i try  to translate into cmd but it is not work well.
![image](https://cloud.githubusercontent.com/assets/11225986/13281690/30597c62-db20-11e5-9f6d-93b950b16f03.png)

**Comment by HereSinceres** [comment]
otherMsg:  
    "angular2": "2.0.0-beta.7",
    "angular2-grid": "^0.4.4",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.33.3",
    "es7-reflect-metadata": "^1.5.5",
    "rxjs": "5.0.0-beta.2", 
    "zone.js": "0.5.15"

**Comment by HereSinceres** [comment]
<div [ngGrid]="gridConfig">
        <div *ngFor="#panel of panels; #i = index" [ngGridItem]="panel.gridItemConfig "> 
        </div>
</div>

gridConfig = {
        'margins': [20],
        'draggable': true,
        'resizable': true,
        'max_cols': 6,
        'max_rows': 0,
        'min_cols': 1,
        'min_rows': 2,
        'cascade': 'up',
        'fix_to_grid': false,
        'auto_style': true,
        'auto_resize': true
    };
panels = [{
                uuid: "1",
                type: "PanelComponent",
                subscriptions: [],
                gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 1, 'row': 1, 'sizex': 3, 'sizey': 1 }
            }, {
                    uuid: "2",
                    type: "PanelComponent",
                    subscriptions: [],
                    gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 4, 'row': 1, 'sizex': 3, 'sizey': 1 }
                }];

**Comment by HereSinceres** [comment]
<div [ngGrid]="gridConfig">
        <div *ngFor="#panel of panels; #i = index" [ngGridItem]="panel.gridItemConfig "> 
        </div>
    </div>
<-------------------------------------------------------------------------------------------------------------------------->
this.gridConfig = {
'margins': [20],
'draggable': true,
'resizable': true,
'max_cols': 6,
'max_rows': 0,
'min_cols': 1,
'min_rows': 2,
'cascade': 'up',
'fix_to_grid': false,
'auto_style': true,
'auto_resize': true
};
this.panels = [{
uuid: "1",
type: "PanelComponent",
subscriptions: [],
gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 1, 'row': 1, 'sizex': 3, 'sizey': 1 }
}, {
uuid: "2",
type: "PanelComponent",
subscriptions: [],
gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 4, 'row': 1, 'sizex': 3, 'sizey': 1 }
}];

**Comment by HereSinceres** [comment]
<-------------------------------------------------------------------------------------------------------------------------->
this.gridConfig = {
'margins': [20],
'draggable': true,
'resizable': true,
'max_cols': 6,
'max_rows': 0,
'min_cols': 1,
'min_rows': 2,
'cascade': 'up',
'fix_to_grid': false,
'auto_style': true,
'auto_resize': true
};
this.panels = [{
uuid: "1",
type: "PanelComponent",
subscriptions: [],
gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 1, 'row': 1, 'sizex': 3, 'sizey': 1 }
}, {
uuid: "2",
type: "PanelComponent",
subscriptions: [],
gridItemConfig: { 'dragHandle': '.handle', 'fixed': true, 'col': 4, 'row': 1, 'sizex': 3, 'sizey': 1 }
}];
```
 <div [ngGrid]="gridConfig">
        <div *ngFor="#panel of panels; #i = index" [ngGridItem]="panel.gridItemConfig "> 
        </div>
    </div>
```

**Comment by BTMorton** [comment]
Hmmm, I haven't tried it with webpack. What's the error you're getting?

**Comment by HereSinceres** [comment]
The Console not show error about ng2-grid

**Comment by HereSinceres** [comment]
can u tried it with webpack. thx.

**Comment by HereSinceres** [comment]
when add code is error：
```
 <div  [ngGridItem]="{'dragHandle': '.title'}" > 
```
but the console print EXCEPTION: No provider for t! (t -> t)

**Comment by vinnybrown** [comment]
Getting a similar issue when using webpack:

unexpected directive value 'undefined' on the View of component 'Home'

where 'Home' is a Component. I have included the directives NgGrid and NgGridItem and I'm importing the directives like so:

import {NgGrid, NgGridItem} from 'angular2-grid';

**Comment by BTMorton** [comment]
Quick update, I've been trying to install one of the angular 2 webpack starter packs, but npm keeps throwing random errors at me. Will update if I have any luck on compiling to webpack format

**Comment by BTMorton** [comment]
OK, the latest npm release is compiled to commonjs, can one of you give this a try with webpack?
