### ISSUE TITLE
I have some bug with grid + route

### ISSUE THREAD

**Issue by mixalbl4-127** [BTMorton/angular2-grid#48]
I created demo:
http://plnkr.co/edit/LezjoViT6EUprocMdR1Y?p=preview

In page plased 3 route: tst 1 tst 2 tst 2
if I click to tst 1 - good
but if I click to tst 2 - in console error:
Uncaught Attempt to use a dehydrated detector: App_route_1_1 -> itemChange
http://s1.micp.ru/puu49.png

Before I used Angular2 beta 0 and grid 0.4.2 - work fine,
now I update Angular2 beta 7 and grid 0.4.4 - work fine, but I have this error on page navigate :(

Excuse me for my bad english
thanks

**Comment by BTMorton** [comment]
Aha, this is because the items are calling removeItem on the grid which is then triggering a resize on each of the remaining items which are then trying to emit an event which obviously won't work. Should be a relatively easy fix :)
