### ISSUE TITLE
Issues with Bootstrap grid-system

### ISSUE THREAD

**Issue by Vrael** [BTMorton/angular2-grid#49]
The grid-item height is not adjust to Boostrap in small screens. If you use for example a Boostrap form in screens with width > 692px every thing is ok. But with less width, the form fields are stacked vertically and grid-item has less height than the real form. I have tested with this config: `[ngGrid]="{'resizeable': false, 'max_cols': 1, 'margins':[0,0,0,0], 'auto_resize': true}"` `[ngGridItem]="{'resizeable': true, 'dragHandle': '.dragHandle', 'resizeHandle': '.resizeHandle'}"`

I think angular2-grid listens screen size changes but this behavior comes from css change style.

**Comment by BTMorton** [comment]
Yes, the default style forces full screen width on smaller devices. It's not the best way of handling responsiveness, I know but at the time, it was all I had! Just remove the `@media` query in NgGrid.css or copy the other styles to your own style sheet. All the required styles should be in the readme
