### ISSUE TITLE
Use Angula2 grid in Angular2 project using Javascript

### ISSUE THREAD

**Issue by kqthang1505** [BTMorton/angular2-grid#50]
Hi @BTMorton ,
I will use angular2 grid for my project, but my project is using Javascript instead of TypeScript. How can I apply the Grid directive to my component? Do you know any tutorials guide me to using that way? Help me please.

Many thanks.

**Comment by BTMorton** [comment]
I'm not sure, I'm afraid having only used it using Typescript.

https://angular.io/docs/js/latest/quickstart.html might help

Basically, in the `ng.core.Component` object, add `directives: [NgGrid, NgGridItem]`, but first you'll need to include those two via system.js. Check out this file for an example: https://github.com/BTMorton/angular2-grid/blob/master/demo/app/app.component.js

Hope that helps!

**Comment by kqthang1505** [comment]
Thanks for your help. :+1:

**Comment by BTMorton** [comment]
Sorry I can't offer you more advice!
