### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by kqthang1505** [BTMorton/angular2-grid#51]
Hi @BTMorton,

Can I add a placeholder box?
Many thanks

**Comment by BTMorton** [comment]
What do you mean by "add a placeholder box"? What are you adding it to exactly?

**Comment by kqthang1505** [comment]
I mean I have a box (like a sample item) on the left, after that I drag and drop it into the drop area and the new item will automaticlly added in to the drop area but the sample box still alive. Can I do that?

**Comment by BTMorton** [comment]
In theory, yes. You'd have to implement the drop logic yourself, but all it would be is essentially creating a new item on the grid. I suppose you could do it by overriding the drag logic as well, but that would be more in depth. You'd have to add the item to the grid then set the dragging item to be said item as soon as they click on the 'placeholder'. If that makes sense?
