### ISSUE TITLE
Crash when resizing the window

### ISSUE THREAD

**Issue by LPalmito** [BTMorton/angular2-grid#54]
I'm trying to build kind of a responsive feature doing that:

```
<div *ngFor='#widget of widgets; #i = index' [ngGridItem]="getGridInfo(widget)">
                    <div *ngIf="widget.permanentInfo.type == 'graph'">
                        <graph-widget [currentWidget]="widget"></graph-widget>
                    </div>
                    <div *ngIf="widget.permanentInfo.type == 'text'">
                        <text-widget [currentWidget]="widget"></text-widget>
                    </div>
</div>
```
where getGridInfo(widget) is a method in my component which returns me the right col, row, sizex, sizey according to the widget and the size of the window.

Everything works perfectly, the display of the widgets and the rescaling of the window, which mimic kind of a responsive feature, except when rescaling from `md` window to `sm` window, which makes all crash and nothing is working anymore.

If you want more information about the methods I'm using in my component:

- to test the size of the window (return true if alias is the size of the window (xs, sm, md or lg):
```
    isBreakpoint(alias) {
        return $('.test-' + alias).is(':visible');
    }
```
- to adapt the total number of columns according to the size of the window:
```
    @HostListener('window:resize')
    loadGrid() {
        if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {this.gridConfig.max_cols = 1;}
        else if (this.isBreakpoint('md')) {this.gridConfig.max_cols = 2;}
        else if (this.isBreakpoint('lg')) {this.gridConfig.max_cols = 3;}
    }
```
- to get the right information concerning col, row, sizex, sizey of each widget according to the size of the window:
```
    getGridInfo(widget) {
        if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {return widget.gridInfo.sm}
        else if (this.isBreakpoint('md')) {return widget.gridInfo.md}
        else if (this.isBreakpoint('lg')) {return widget.gridInfo.lg}
    }
```
Like I said before, every rescaling is working except `md`>`sm`, which means: `xs`>`sm`, `sm`>`md`, `md`>`lg`, `lg`>`md` and `sm`>`xs` are working.

**Comment by BTMorton** [comment]
Can you try to reproduce it in a plunkr? It all seems to be working in my test/demo pages, so I can only imagine it's something you're end. I'm happy to take a look if you can give me a working example

**Comment by LPalmito** [comment]
I've tried to make a plunker but it is not working properly: `EXCEPTION: No provider for NgGrid! (NgGridItem -> NgGrid)` (http://plnkr.co/edit/y3QgzptqtCEN0Apy4Syj?p=preview). Can you help me on that so I can show you the issue I encounter with angular-2-grid please?

**Comment by BTMorton** [comment]
You haven't wrapped the [ngGridItem]s with an [ngGrid]. Add that as a containing div and it'll fix that error.

**Comment by LPalmito** [comment]
You're right, here is my new plunker: http://plnkr.co/edit/y3QgzptqtCEN0Apy4Syj?p=preview.

The problem I encounter now is that, no matter what is the effective size of the window, it tells me that it is `sm` or `xs`, so I can't reproduce the bug I'm telling you. I've tried something with 3 buttons to "artificially resize the window", which I have not found really useful (in comments in my code).

Hope it can help you!

**Comment by BTMorton** [comment]
You didn't include the bootstrap CSS which is why it wasn't working. I managed to reproduce the bug and I think it's because it's trying to set the max_cols to be less than the sizex of one of it's widgets and so entering an endless loop. I'll try to take a look this evening and see if I can put in a catch for that.

**Comment by LPalmito** [comment]
OK, it was effectively it, thanks for help. Now that I know that, I can formulate my issue from an other point of view. I still want to be able to resize my widgets and the `max_cols` when the window is resized by the user but I need to resize:
- first, the `sizex` of the widgets
- only after that, `max_cols`
(and I was doing it the other way around until now)

So I need to know when all the `sizex` of my widgets are modified, and I haven't been able to access that info so far. I've tried to use `resizeStop`, to update an array of booleans, but the event is triggered only if the user is resizing the widgets, not if it is a result of resizing the window, as it is in my example. Is there a way to catch that event? I haven't find one in the current possibilities. Do you want me to open a new post for that issue?

Her is what I've tried:

```
// The array of booleans
private isResizingSafe = [];

// The modified loadGrid() method
@HostListener('window:resize')
    loadGrid() {
        if (this.isResizingSafe.every(element => element == true)) {
            if (this.isBreakpoint('lg')) {this.gridConfig.max_cols = 3;}
            else if (this.isBreakpoint('md')) {this.gridConfig.max_cols = 2;}
            else if (this.isBreakpoint('sm') || this.isBreakpoint('xs')) {this.gridConfig.max_cols = 1;}
            this.isResizingSafe.fill(false);
        }
    }

// The resized(i) method, launched when resizeStop is triggered
resized(i) {
        this.isResizingSafe[i] = true;
    }
```

Thanks a lot for your help!

**Comment by LPalmito** [comment]
Yeaaah, thanks a lot, it's perfectly working!
