### ISSUE TITLE
demo is not functional

### ISSUE THREAD

**Issue by gog182** [BTMorton/angular2-grid#55]
boxes are not instantiated

**Comment by BTMorton** [comment]
What URL are you trying to access?

**Comment by gog182** [comment]
I'm using: https://github.com/BTMorton/angular2-grid/tree/master/demo/* (couldn't find any "boxes", so I had to create it)
Can't you put your live demo code instead (the one under: https://bmorton.co.uk/angular/)?
Thx for the quick reply.

**Comment by BTMorton** [comment]
The code for https://bmorton.co.uk/angular/ is available at https://github.com/BTMorton/angular2-grid/tree/master/src it's the app.* files. The stuff under the demo folder is at https://bmorton.co.uk/angular_test/ and it's one I use for sanity checking my npm release and debugging :)

**Comment by gog182** [comment]
definitely, you are right. thanks a lot!
