### ISSUE TITLE
Can not run with webpack?

### ISSUE THREAD

**Issue by baonguyenyam** [BTMorton/angular2-grid#58]
Hi Ad!
This plugins can not run with webpack ("module": "commonjs") ?

**Comment by BTMorton** [comment]
OK, the latest npm release is compiled to commonjs, can you give this a try with webpack?

**Comment by baonguyenyam** [comment]
Hi BTMorton!
When i import NgGrid and run with webpack it notice as 'System is not defined"
![screen shot 2016-03-31 at 9 50 56 am](https://cloud.githubusercontent.com/assets/3025550/14164115/b812ac9c-f726-11e5-8e8c-dd7d95b8b057.png)

**Comment by BTMorton** [comment]
What version is that using? v0.5.2 doesn't compile system anymore so you should be able to use it like any other commonjs module...
