### ISSUE TITLE
Variable width of columns to fit window width

### ISSUE THREAD

**Issue by ClaudiaKr** [BTMorton/angular2-grid#59]
Hi, 
If it's possible: What would be the best way to stretch/squeeze a fixed number of columns into the given page width?
I need to avoid horizontal scrolling.
Thank you.

**Comment by BTMorton** [comment]
If you set the config values `max_cols` to the number of columns you want and then set `auto_resize` to true, it will set the column widths so that `max_cols` worth of columns fill the container. Make sure the container has width 100% and you should be good :)

**Comment by ClaudiaKr** [comment]
Thanks, thats almost the behavior I need,
but there seems to be a bug with max_cols: when dragging an item into an already full row the last item does not wrap into the next row and remains shifted up to column max_cols + 1.

I would also need to change the rowHeight on resize, so that for example two rows are completely visible at a time. I understand that max_rows and max_cols are not allowed at the same time but what about max_cols and max_visible_rows?

**Comment by ClaudiaKr** [comment]
Visible rows / columns are working perfect - thanks.

**Comment by BTMorton** [comment]
https://www.youtube.com/watch?v=VZWTZdMpz3M
