### ISSUE TITLE
unable to start angular2-grid-master/demo

### ISSUE THREAD

**Issue by bibermar** [BTMorton/angular2-grid#61]
I unzipped angular2-grid-master.zip, went to ../angular2-grid-master/demo folder and ran:
$ npm start
It resulted in error detailed in below npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular2-quickstart@1.0.0
6 info start angular2-quickstart@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular2-quickstart@1.0.0 Failed to exec start script
9 verbose stack Error: angular2-quickstart@1.0.0 start: `concurrently "npm run tsc:w" "npm run lite" `
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid angular2-quickstart@1.0.0
11 verbose cwd C:\Users\RB28112\angular2-grid-master\demo
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error angular2-quickstart@1.0.0 start: `concurrently "npm run tsc:w" "npm run lite" `
17 error Exit status 1
18 error Failed at the angular2-quickstart@1.0.0 start script 'concurrently "npm run tsc:w" "npm run lite" '.
18 error This is most likely a problem with the angular2-quickstart package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     concurrently "npm run tsc:w" "npm run lite"
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs angular2-quickstart
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls angular2-quickstart
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

Can someone pleas help?
Thanks in advance.

**Comment by BTMorton** [comment]
Did you run npm install first?

**Comment by bibermar** [comment]
You mean npm install –dev?
Where it should be run: in angular2-grid-master directory?
I’m new in Angular, sorry

**Comment by bibermar** [comment]
You mean npm install –dev?
Where it should be run: in angular2-grid-master directory?
I’m new in Angular, sorry

**Comment by bibermar** [comment]
I actually install nodejs & npm in C:\\Program Files (x86)\\nodejs; npm was installed and it produced error log above saying the problem "not with npm itself but... most likely a problem with the angular2-quickstart package"

**Comment by BTMorton** [comment]
In angular2-grid-master/demo run npm install and it should (he says...) work

**Comment by bibermar** [comment]
yes, it did work - thanks a lot, but I see no grid - it mostly empty screen - see attach. I also see 404 on favicon.ico, but don't think it's the cause
[AngularGridEmpty.docx](https://github.com/BTMorton/angular2-grid/files/207260/AngularGridEmpty.docx)

**Comment by BTMorton** [comment]
The white box inside the big grey one? Yeah, that's the only item in there by default :P If you're looking for the main demo at https://bmorton.co.uk/angular/ it's not the demo. That's part of the source in the main repo

**Comment by bibermar** [comment]
Thanks. Is there any way to get real grid demo to see how it looks/works?

**Comment by bibermar** [comment]
so https://bmorton.co.uk/angular/ is the real demo?

**Comment by BTMorton** [comment]
That's the full demo yeah. To use that is a bit more complex. It doesn't come with a web server like the demo. (all in angular-grid-master/) You'll have to run `npm install`, then `npm install -g gulp`, `gulp build` and then if you need a web server `npm install -g lite-server` and then `lite-server`

**Comment by bibermar** [comment]
I did  **npm install -g gulp** had no errors only warnings, but gulp build gave me below:
 ...\angular2-grid-master\demo> gulp build
[16:50:37] Local gulp not found in ~\angular2-grid-master
[16:50:37] Try running: npm install gulp

after npm install gulp, the same on gulp build: Local gulp not found...
And when I ran  lite-server, it gave me that same empty screen

**Comment by BTMorton** [comment]
you need to be in \angular2-grid-master\ not \angular2-grid-master\demo and then run those commands :P

**Comment by bibermar** [comment]
running 'gulp build' yields below: (also not mentioned in the stack besides 'gulp-rename', gulp-symlink missing according  gulpfile.js )
C:\Users\RB28112\angular2-grid-master>gulp build
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-rename'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\RB28112\angular2-grid-master\gulpfile.js:5:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by Luchillo** [comment]
For me too, had to install the gulp plugins lacking, it's just that some gulp plugins weren't saved to `package.json`.

**Comment by BTMorton** [comment]
Will update package.json, thanks I hadn't noticed!

**Comment by Luchillo** [comment]
Btw, non related, how do i get the grid instance in order to call the functions that you expose in the api?

**Comment by BTMorton** [comment]
Honestly? I don't know :P Where it's set up as a Directive rather than a Component it doesn't seem to be injected the same way. Where I'd usually just do `constructor(private _ngGrid: NgGrid) { }` which would get it, it throws an error :/ For v1 proper, I might change this around, but obviously that might cause a few headaches :D

@bibermar if you're still having problems, the two missing packages are now in latest :)

**Comment by Luchillo** [comment]
@BTMorton Most likely will have to bind to the functions from html, however if that doesn't work you most likely will have to make a controller (injectable) for the directive.

**Comment by BTMorton** [comment]
Yeah, most likely. There aren't that many functions that are of use to a parent component as most of the public functions are for communicating between the grid and items. I've tried to expose enough events that they aren't necessary and the relevant information changes can be gathered by listening to them. If you have any requests/suggestions for more, feel free to open a new issue :)

**Comment by Luchillo** [comment]
Well, the one i'm trying to reach is serialization, to be able to save the new position of the items to a database so that users can customize their layout and the changes stay even in next sessions.

**Comment by BTMorton** [comment]
I have a component for each of the items that embeds the NgGridItem directive, listens to the drag/resize events and then stores the reference that can then be got later to serialize. That component then handles loading/resizing/etc. of the actual item content. Hope that helps?

**Comment by Luchillo** [comment]
Yeah i expected as much just that i couldn't understand how to get that from the docs.

**Comment by BTMorton** [comment]
Closing this issue as I'm assuming you got it working @bibermar. Any more issues, feel free to let me know!
