### ISSUE TITLE
[Bug] Webpack and A2 require error

### ISSUE THREAD

**Issue by Luchillo** [BTMorton/angular2-grid#62]
Hi, i just installed from npm the last version at the moment v-0.5.2 in an A2-webpack project, it transpile as expected however i get this error in browser:
```js
NgGrid.min.js:1 Uncaught ReferenceError: require is not defined
```

**Comment by Luchillo** [comment]
Ok i see the issue, i had no parse for minified files in my webpack config file, however this should not be the case, a minified file should not have a require in it, i have to add the `noParse` regex like this to parse NgGrid.min.js:
```js
noParse: [
    /(?!NgGrid)\.min\.js/,
    /vendor[\/\\].*?\.(js|css)$/
    // /socket.io-client/
  ]
```

**Comment by Luchillo** [comment]
Actually the noParse doesn't work either unless i erase the full line for `min.js` extentions, i had to require it like this in order to sort this issue, i guess this way is forcing the not minified version which its being parsed?:
```ts
import { NgGrid, NgGridItem } from 'angular2-grid/dist/NgGrid';
```

**Comment by BTMorton** [comment]
I'm gonna run it through this instead of uglify for the next release, think it'll fix it? I've not been able to get webpack to actually run yet so don't have a proper test bed :P

https://www.npmjs.com/package/gulp-requirejs-optimize

**Comment by Luchillo** [comment]
The issue is it was Uglyfied, not bundled, i'm mostly over Webpack so not sure if using that gulp plugin will do but trying doesn't hurt.

**Comment by BTMorton** [comment]
OK, compiled to umd this time, which will hopefully resolve it (fingers crossed!). Give v0.5.3 a go (assuming you still have a webpack package somewhere)

**Comment by Luchillo** [comment]
Sorry, can't until monday, PC in office :(

**Comment by BTMorton** [comment]
No worries, no rush :)

**Comment by Luchillo** [comment]
Tested 0.5.3 no luck, still pops out the require error.

**Comment by Luchillo** [comment]
Actually not only it doesn't fix the issue but broke my app, now importing like:
```js
import { NgGrid, NgGridItem } from 'angular2-grid/dist/NgGrid'
```
Gives error:
```js
Uncaught Error: Cannot find module 'angular2/core'.
```

**Comment by BTMorton** [comment]
Ha! Fantastic! I hate webpack...

**Comment by BTMorton** [comment]
OK, so I'm out of ideas. Every time I try to bundle it with requirejs or whatever, it still give me either exactly the same file or just a file with the require in. I've reverted back to commonjs for 0.5.4, but updated package.json to point at the main .js file, rather than the minified one. Hopefully, that will resolve your issue

**Comment by BTMorton** [comment]
@Luchillo Did everything work OK with that change? Am I ok to close this?

**Comment by Luchillo** [comment]
Sorry, i'm away from my laptop until monday, i'll let you know if latest version solves the issue.

**Comment by Luchillo** [comment]
I'm sorry to answer so late, i tested extensively with the latest version and it works like a charm, im closing this issue right NOW.
