### ISSUE TITLE
width vs min_width & height vs min_height

### ISSUE THREAD

**Issue by filoucpp** [BTMorton/angular2-grid#69]
Hi all!

I've been playing with this grid for a while now. I really like it but there is something I still can't figure out: what are min_width and min_height supposed to do?

Thanks a lot in advance!
Philippe

**Comment by BTMorton** [comment]
Hey! So the min_width and min_height values are the smallest possible width/height that the items can be. This means that when you're resizing items, they won't go smaller than that. Also, it will override the min_rows/min_cols value that you set. If your col_width/row_height is 50 and your min_width/min_height is 180, your min_rows/min_cols value will be 4.

col_width/row_height is the size for each column/row (if you don't use max_rows/max_cols or visible_rows/visible_cols, that is). They don't get overwritten by the min_width/min_height values, but the min_rows/min_cols values get set (if not already). You can have min_cols/min_rows greater than that set by the min_width/min_height, which means that they'll then just affect the smallest size you can drag items to.

Sorry, that's kinda gibberish... Does that all make sense?

**Comment by filoucpp** [comment]
thanks for the quick answer. It makes sense and it is was I understood. Although when I play with it I put a min_width of let's say 250 (which is pixels correct?) and if I resize my browser I get items that go smaller than that value... hence my question :)

I'll go back in my code to verify but looking at this demo (https://bmorton.co.uk/angular/) and it does the same thing

**Comment by filoucpp** [comment]
writing this I just realized that you're probably talking about resize by user input on the item, not resize of the window... my mistake! What I'm trying to do is prevent a column to go too small because my content get messed up inside...

**Comment by BTMorton** [comment]
Yeah, you're right. I think something has gotten screwed up somewhere. I'll take a look at the resize and config update stuff, to see if I can figure out what's going on :)

**Comment by filoucpp** [comment]
that's great thanks!!!
