### ISSUE TITLE
Trying to run demo, browser tab hangs

### ISSUE THREAD

**Issue by dtaub** [BTMorton/angular2-grid#71]
I cloned the repo, `cd`'ed into the demo directory ran `npm install` and `npm start`. I got a bunch of TypeScript errors and when it launched Chrome the tab just hangs on Loading... with no indication of an error in the server log. In Firefox it makes it to showing the app with the message and grid item but then it says a script stopped responding.

This is on Ubuntu 15.10, nodejs 5.11.0, angular 2.0.0-beta.15, angular2-grid 0.5.7

**Comment by Radu-Dunarentu** [comment]
same issue here, w10, node 5.7

**Comment by BTMorton** [comment]
Yes... at a guess I'd say it's because I haven't updated it to the latest version of angular and something has changed. I'll get on it!

**Comment by BTMorton** [comment]
OK, demo should be fixed with the latest version. Note: I've upgraded it to angular beta 16 now, so you'll need to up that too.

**Comment by BTMorton** [comment]
6748e82 for reference
