### ISSUE TITLE
Error with beta 15

### ISSUE THREAD

**Issue by ghaiat** [BTMorton/angular2-grid#72]
When running with beta 15, i have the following errors:
````
error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<NgGridItem>'
`````

can you update the following lines:
````
public dragStart: EventEmitter<NgGridItem> = new EventEmitter();
````

to

````
public dragStart: EventEmitter<NgGridItem> = new EventEmitter<NgGridItem> ();
````

?

Thanks

**Comment by BTMorton** [comment]
Which version of Typescript are you using? I don't get the same error. Will see if it breaks things here...

**Comment by ghaiat** [comment]
typescript": "1.9.0-dev.20160409” like angular

-- 
Gilles Haiat

On 27 April 2016 at 23:02:06, Ben Morton (notifications@github.com) wrote:

Which version of Typescript are you using? I don't get the same error. Will see if it breaks things here...
