### ISSUE TITLE
when resize grid item, the resizingItem item waggle?

### ISSUE THREAD

**Issue by unlimit-ed** [BTMorton/angular2-grid#74]
when resizing a grid item, the resizingItem is wagging.  
maybe this is a bug, because the previous version this effect is ok.

**Comment by BTMorton** [comment]
Yeah, this is definitely a bug, but an interesting one. The resize event of the NgGrid is being caught by the window:resize hook, triggering all the items to recalculate themselves. I'll rename the events and that should fix it. No idea why that's happened though :S

**Comment by unlimit-ed** [comment]
thanks a lot!
