### ISSUE TITLE
[FR] Zoom Out on Drag

### ISSUE THREAD

**Issue by amcdnl** [BTMorton/angular2-grid#77]
Love the project; had an idea wanted to get your feedback.

So essentially when you have a lot of items on your grid, it gets difficult to drag/reorganize. This is a interesting concept:

![drag](https://logrhythm.com/images/screen-shots/siem.gif)

When you start dragging, it zooms out so you can re-organize them better.

**Comment by maxtuzz** [comment]
+1

**Comment by DanGeffroy** [comment]
:+1:

**Comment by BTMorton** [comment]
Closed as of 0238a2b4a48f1429450aff7007c8a56705cddf5f

**Comment by amcdnl** [comment]
Thats awesome @BTMorton! Thanks!
