### ISSUE TITLE
Click event prevented

### ISSUE THREAD

**Issue by hmlb** [BTMorton/angular2-grid#81]
Hi,

I have grid items ( cards ) that can be dragged and dropped on a grid by a handle (card's illustration).    
When the user clicks the illustration instead of dragging it, i want to perform an action.  

But the click events are "canceled" when it occurs on an element that is a "handle" for drag and drop.  

In the example below, "awesomeStuff()" ever happens :   

```
<div ...gridConfiguration>
    <div *ngFor="#item of items"
             [ngGridItem]="item.config"
             (click)="awesomeStuff()"
             (onDragStop)="onChange($event, item)">
        <img ... (click)="awesomeStuff()"/>
    </div>
</div>
```

Any idea on how to make this work ?

Thanks,

**Comment by BTMorton** [comment]
Hmmm, I've tried this on my setup and it seems to work fine, with a simple example. Can you demonstrate it with a plunkr so I can try to investigate?

**Comment by wuhkuh** [comment]
Yes! I managed to reproduce this example. This ONLY occurs when draggable is equal to 'true'. Setting it to false makes us able to edit the input.

**Comment by wuhkuh** [comment]
I fixed it! Incoming solution.

**Comment by hmlb** [comment]
Thanks a lot @wuhkuh , I have been swamped and had no time to work on this issue since I opened it

**Comment by wuhkuh** [comment]
@hmlb No problem! 
I am having a small issue which is caused by the fix though, but I'll get it done later this evening. Don't worry about it.

**Comment by wuhkuh** [comment]
@hmlb 
I made a new **pull request** containing a fix for the issue. Please review :)
