### ISSUE TITLE
Break the project into multiple files

### ISSUE THREAD

**Issue by tudorgergely** [BTMorton/angular2-grid#83]
Right now there is one big file with all the directives and interfaces. I suggest we brake it in multiple files/folders so we have better maintainability in the future.

What I suggest (since this is not a big library) is something like:

- app
  - directives
    - ng-grid
      - NgGrid
      - NgGridConfig
      - NgGridPlaceholder
    - ng-grid-item
      - NgGridItem
      - NgGridItemConfig
      - NgGridItemEvent

Also, breaking NgGrid class even further (in multiple services and such would be a plus)

**Comment by BTMorton** [comment]
Yes, it's not the nicest/most maintainable library ever.

I would say that it should be a single level project still. The actual application can be moved into it's own ecosystem linking in NgGrid if need be, but I'd like to keep the library seperate from the app, so potentially with a layout like:

- src
    - NgGrid
    - NgGridItem
    - NgGridPlaceholder
    - INgGrid
    - (INgGridItem?)

The interfaces don't need to all be in a separate file. 

What I would like it to keep it compiling to a single file. It's not the end of the world if it doesn't, that's just my personal preference. That may need a fair bit of re-factoring in the build process.

How would you suggest splitting it further? Which services etc. would you split out?

**Comment by tudorgergely** [comment]
I would extract the dragging in a separate service. That way we could also drag an item from a grid to another (by using the service). 

What should this service do:

1. Receive an item that started dragging
2. Move the item after the mouse
3. Emit events onmouseup, onmousemove etc so the grids can react accordingly.

Maybe we can break it even more but I have to study it a little further before I can say.

**Comment by BTMorton** [comment]
Yeah, that's definitely a viable option. Another thought I had was converting the cascade into a service so that it could be easily switched out with a different implementation, but that could get confusing as it would need to have access to the internal grid representation... More thought required there methinks
