### ISSUE TITLE
Demo Website first load time crippled....286 xhr requests....25 seconds of white screen

### ISSUE THREAD

**Issue by dharders** [BTMorton/angular2-grid#88]
Just checked out your demo website: [https://bmorton.co.uk/angular/](https://bmorton.co.uk/angular/)

First time visit I thought something was broken as blank white screen. So I opened Chrome Dev Tools...no console errors. Switching to network tab, could see it churning away still downloading appropriate modules. There were 286 xhr requests and it had taken 25 seconds before I saw anything on screen.

It's probably most likely due to the new Angular rc module bundling. Are you packaging all vendor scripts together? The extra xhr round trips are crippling 'first visit' load times.

Subsequent visits to the website are fine, as the browser cache is doing its thing!

To reproduce:  
- Open Chrome Dev Tools
- Go to network tab and ensure 'Disable Cache' is checked
- Reload your website [https://bmorton.co.uk/angular/](https://bmorton.co.uk/angular/)

I haven't played with the new rc yet (still using beta17) but surely there's a way to bundle the scripts into one package and let SystemJS do it's thing on the client side.

At the very least, I guess you could put in a spinner ;)

**Comment by BTMorton** [comment]
Hey @dharders,

Yes, I think this is a Angular 2 RC change. It moves everything into separate npm packages and (last I checked) don't have bundles yet... I'll have a look and see if there's an easy way to get round it, but I don't want to move to webpack if I don't have to.

To google!
