### ISSUE TITLE
Nested

### ISSUE THREAD

**Issue by Olexiy665** [BTMorton/angular2-grid#92]
Can I create nested NgGrid into the NgGridItem?

**Comment by BTMorton** [comment]
I've never tried it, but in theory it should work. If you create an handle on the container item so that it doesn't try to drag the outer item when you drag a nested item, it should work fine :+1:

**Comment by Olexiy665** [comment]
Thank you. I tried  it on the beta0-17 and got an error. But now(on rc1) it works fine!
