### ISSUE TITLE
Error running with Angular-cli

### ISSUE THREAD

**Issue by pdfarhad** [BTMorton/angular2-grid#93]
I tried to install angular2-grid with angular-cli. My Angular-cli's angular 2 version is 2.0.0-rc.1. Can you please help me out with this issue. I am stuck here for 2 days, It is throwing me this error.

`    zone.js:101 GET http://localhost:4200/node_modules/angular2-grid/dist/NgGrid 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM6591:3fetchTextFromURL @ system.src.js:1154(anonymous function) @ system.src.js:1735ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:1734(anonymous function) @ system.src.js:2759(anonymous function) @ system.src.js:3333(anonymous function) @ system.src.js:3600(anonymous function) @ system.src.js:3985(anonymous function) @ system.src.js:4448(anonymous function) @ system.src.js:4700(anonymous function) @ system.src.js:406ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-grid/dist/NgGrid
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/angular2-grid/dist/NgGrid as "angular2-grid" from http://localhost:4200/app/banbeis.component.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-grid/dist/NgGrid(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/angular2-grid/dist/NgGrid(…)`

**Comment by BTMorton** [comment]
Ah, yes, sorry forgot to update the readme when I split the files. The line in your SystemJS config maps for this should now be:

```
'angular2-grid': 'node_modules/angular2-grid/dist/main'
```

Hopefully that will solve it. I'll update the README ASAP!

**Comment by pdfarhad** [comment]
It didnt help me , Did you manage to install this plugin with Angular-cli ?

**Comment by BTMorton** [comment]
I have not yet used angular-cli, so I don't know the specifics of how to run it. However, from your stack trace I can see that it's an issue with the System.js import. Which version of angular2-grid are you using? Do you have defaultJSExtensions turned on in SystemJS?

**Comment by BTMorton** [comment]
Check your system.js config against the latest readme. That should solve it :)

**Comment by pdfarhad** [comment]
![screen shot 2016-06-06 at 12 33 45 am](https://cloud.githubusercontent.com/assets/5729457/15807163/20d4bc0e-2b78-11e6-8c02-00d6f9c43d9e.png)

This is what I get when i tried to "npm install angular2-grid" .  You see here ,in my app package the version of angular2 is showing . I am new to Angular , so can you please guide me to achieve this :)

**Comment by BTMorton** [comment]
Ok, that's an interesting npm error set... I'd recommend maybe clearing your node modules and re-installing or at the very least trying `npm uninstall angular2`. I don't know exactly where the rxjs complaint is coming from, I'll admit. Everything in the pipeline has the correct dependencies set. Yaaay confusion... I hope that helps!

**Comment by pdfarhad** [comment]
Fact is , using angular-cli it creates the project with 
`ng new "project-name"`
What it does is , it creates the project structure and does `npm install` inside the folder, so it comes automatically with angular-cli.
I know , I am maybe saying weird things but can you give a shot with angular-cli. I am desperate to use your library but not finding any way to do it :( 

Thanks anyway

**Comment by BTMorton** [comment]
OK, so I have no idea why the install didn't work correctly. For me, once I got past a few system setup hurdles, everything installed fine. Then what I had to do was add to:

angular-cli-build.js
```
...
    vendorNpmFiles: [
      ...
      'angular2-grid/dist/**/*.js'
      ...
```

system-configs.ts
```
/** Map relative paths to URLs. */
const map: any = {
	'angular2-grid': 'vendor/angular2-grid/dist'
};

/** User packages configuration. */
const packages: any = {
	'angular2-grid': { main: 'main.js',  defaultExtension: 'js' }
};
```

The cli does some weird bundling, hence the many error. Sorry it took so long to get to the bottom of this. Hopefully, this'll solve your problems!

**Comment by pdfarhad** [comment]
Thanks , the issue is fixed

**Comment by candidature** [comment]
I faced exactly same issue with rc.4 of angular and latest downloads from npm repo. Luckily i got "BTMorton comment on 6 Jun"  which solved my issue. Before this i wasted couple of hours just to find fix of this issue.

**Comment by fonzy2013** [comment]
I followed the above suggestions with angular-cli 1.0.0-beta.26 and get `ERROR in NgGridModule is not an NgModule`. 

angular-cli has changed also to using webpack. If anyone could point me to how to get it working it would be great.
